# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/c_byrne/projects/komorebi-pruned-nmonitors

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/c_byrne/projects/komorebi-pruned-nmonitors

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/c_byrne/projects/komorebi-pruned-nmonitors/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/c_byrne/projects/komorebi-pruned-nmonitors/CMakeFiles /home/c_byrne/projects/komorebi-pruned-nmonitors//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/c_byrne/projects/komorebi-pruned-nmonitors/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named komorebi

# Build rule for target.
komorebi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 komorebi
.PHONY : komorebi

# fast build rule for target.
komorebi/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/komorebi.dir/build.make CMakeFiles/komorebi.dir/build
.PHONY : komorebi/fast

src/Main.o: src/Main.c.o
.PHONY : src/Main.o

# target to build an object file
src/Main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/komorebi.dir/build.make CMakeFiles/komorebi.dir/src/Main.c.o
.PHONY : src/Main.c.o

src/Main.i: src/Main.c.i
.PHONY : src/Main.i

# target to preprocess a source file
src/Main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/komorebi.dir/build.make CMakeFiles/komorebi.dir/src/Main.c.i
.PHONY : src/Main.c.i

src/Main.s: src/Main.c.s
.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/komorebi.dir/build.make CMakeFiles/komorebi.dir/src/Main.c.s
.PHONY : src/Main.c.s

src/OnScreen/AssetActor.o: src/OnScreen/AssetActor.c.o
.PHONY : src/OnScreen/AssetActor.o

# target to build an object file
src/OnScreen/AssetActor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/komorebi.dir/build.make CMakeFiles/komorebi.dir/src/OnScreen/AssetActor.c.o
.PHONY : src/OnScreen/AssetActor.c.o

src/OnScreen/AssetActor.i: src/OnScreen/AssetActor.c.i
.PHONY : src/OnScreen/AssetActor.i

# target to preprocess a source file
src/OnScreen/AssetActor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/komorebi.dir/build.make CMakeFiles/komorebi.dir/src/OnScreen/AssetActor.c.i
.PHONY : src/OnScreen/AssetActor.c.i

src/OnScreen/AssetActor.s: src/OnScreen/AssetActor.c.s
.PHONY : src/OnScreen/AssetActor.s

# target to generate assembly for a file
src/OnScreen/AssetActor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/komorebi.dir/build.make CMakeFiles/komorebi.dir/src/OnScreen/AssetActor.c.s
.PHONY : src/OnScreen/AssetActor.c.s

src/OnScreen/BackgroundWindow.o: src/OnScreen/BackgroundWindow.c.o
.PHONY : src/OnScreen/BackgroundWindow.o

# target to build an object file
src/OnScreen/BackgroundWindow.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/komorebi.dir/build.make CMakeFiles/komorebi.dir/src/OnScreen/BackgroundWindow.c.o
.PHONY : src/OnScreen/BackgroundWindow.c.o

src/OnScreen/BackgroundWindow.i: src/OnScreen/BackgroundWindow.c.i
.PHONY : src/OnScreen/BackgroundWindow.i

# target to preprocess a source file
src/OnScreen/BackgroundWindow.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/komorebi.dir/build.make CMakeFiles/komorebi.dir/src/OnScreen/BackgroundWindow.c.i
.PHONY : src/OnScreen/BackgroundWindow.c.i

src/OnScreen/BackgroundWindow.s: src/OnScreen/BackgroundWindow.c.s
.PHONY : src/OnScreen/BackgroundWindow.s

# target to generate assembly for a file
src/OnScreen/BackgroundWindow.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/komorebi.dir/build.make CMakeFiles/komorebi.dir/src/OnScreen/BackgroundWindow.c.s
.PHONY : src/OnScreen/BackgroundWindow.c.s

src/OnScreen/DateTimeBox.o: src/OnScreen/DateTimeBox.c.o
.PHONY : src/OnScreen/DateTimeBox.o

# target to build an object file
src/OnScreen/DateTimeBox.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/komorebi.dir/build.make CMakeFiles/komorebi.dir/src/OnScreen/DateTimeBox.c.o
.PHONY : src/OnScreen/DateTimeBox.c.o

src/OnScreen/DateTimeBox.i: src/OnScreen/DateTimeBox.c.i
.PHONY : src/OnScreen/DateTimeBox.i

# target to preprocess a source file
src/OnScreen/DateTimeBox.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/komorebi.dir/build.make CMakeFiles/komorebi.dir/src/OnScreen/DateTimeBox.c.i
.PHONY : src/OnScreen/DateTimeBox.c.i

src/OnScreen/DateTimeBox.s: src/OnScreen/DateTimeBox.c.s
.PHONY : src/OnScreen/DateTimeBox.s

# target to generate assembly for a file
src/OnScreen/DateTimeBox.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/komorebi.dir/build.make CMakeFiles/komorebi.dir/src/OnScreen/DateTimeBox.c.s
.PHONY : src/OnScreen/DateTimeBox.c.s

src/Utilities.o: src/Utilities.c.o
.PHONY : src/Utilities.o

# target to build an object file
src/Utilities.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/komorebi.dir/build.make CMakeFiles/komorebi.dir/src/Utilities.c.o
.PHONY : src/Utilities.c.o

src/Utilities.i: src/Utilities.c.i
.PHONY : src/Utilities.i

# target to preprocess a source file
src/Utilities.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/komorebi.dir/build.make CMakeFiles/komorebi.dir/src/Utilities.c.i
.PHONY : src/Utilities.c.i

src/Utilities.s: src/Utilities.c.s
.PHONY : src/Utilities.s

# target to generate assembly for a file
src/Utilities.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/komorebi.dir/build.make CMakeFiles/komorebi.dir/src/Utilities.c.s
.PHONY : src/Utilities.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... komorebi"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/OnScreen/AssetActor.o"
	@echo "... src/OnScreen/AssetActor.i"
	@echo "... src/OnScreen/AssetActor.s"
	@echo "... src/OnScreen/BackgroundWindow.o"
	@echo "... src/OnScreen/BackgroundWindow.i"
	@echo "... src/OnScreen/BackgroundWindow.s"
	@echo "... src/OnScreen/DateTimeBox.o"
	@echo "... src/OnScreen/DateTimeBox.i"
	@echo "... src/OnScreen/DateTimeBox.s"
	@echo "... src/Utilities.o"
	@echo "... src/Utilities.i"
	@echo "... src/Utilities.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

