/* AssetActor.c generated by valac 0.56.13, the Vala compiler
 * generated from AssetActor.vala, do not modify */

#include <clutter/clutter.h>
#include <glib-object.h>
#include <glib.h>
#include <gtk/gtk.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <stdlib.h>
#include <string.h>
#include <cogl/cogl.h>
#include <gio/gio.h>
#include <float.h>
#include <math.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define KOMOREBI_ON_SCREEN_TYPE_ASSET_ACTOR (komorebi_on_screen_asset_actor_get_type ())
#define KOMOREBI_ON_SCREEN_ASSET_ACTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KOMOREBI_ON_SCREEN_TYPE_ASSET_ACTOR, KomorebiOnScreenAssetActor))
#define KOMOREBI_ON_SCREEN_ASSET_ACTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KOMOREBI_ON_SCREEN_TYPE_ASSET_ACTOR, KomorebiOnScreenAssetActorClass))
#define KOMOREBI_ON_SCREEN_IS_ASSET_ACTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KOMOREBI_ON_SCREEN_TYPE_ASSET_ACTOR))
#define KOMOREBI_ON_SCREEN_IS_ASSET_ACTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KOMOREBI_ON_SCREEN_TYPE_ASSET_ACTOR))
#define KOMOREBI_ON_SCREEN_ASSET_ACTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KOMOREBI_ON_SCREEN_TYPE_ASSET_ACTOR, KomorebiOnScreenAssetActorClass))

typedef struct _KomorebiOnScreenAssetActor KomorebiOnScreenAssetActor;
typedef struct _KomorebiOnScreenAssetActorClass KomorebiOnScreenAssetActorClass;
typedef struct _KomorebiOnScreenAssetActorPrivate KomorebiOnScreenAssetActorPrivate;

#define KOMOREBI_ON_SCREEN_TYPE_BACKGROUND_WINDOW (komorebi_on_screen_background_window_get_type ())
#define KOMOREBI_ON_SCREEN_BACKGROUND_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KOMOREBI_ON_SCREEN_TYPE_BACKGROUND_WINDOW, KomorebiOnScreenBackgroundWindow))
#define KOMOREBI_ON_SCREEN_BACKGROUND_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KOMOREBI_ON_SCREEN_TYPE_BACKGROUND_WINDOW, KomorebiOnScreenBackgroundWindowClass))
#define KOMOREBI_ON_SCREEN_IS_BACKGROUND_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KOMOREBI_ON_SCREEN_TYPE_BACKGROUND_WINDOW))
#define KOMOREBI_ON_SCREEN_IS_BACKGROUND_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KOMOREBI_ON_SCREEN_TYPE_BACKGROUND_WINDOW))
#define KOMOREBI_ON_SCREEN_BACKGROUND_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KOMOREBI_ON_SCREEN_TYPE_BACKGROUND_WINDOW, KomorebiOnScreenBackgroundWindowClass))

typedef struct _KomorebiOnScreenBackgroundWindow KomorebiOnScreenBackgroundWindow;
typedef struct _KomorebiOnScreenBackgroundWindowClass KomorebiOnScreenBackgroundWindowClass;
enum  {
	KOMOREBI_ON_SCREEN_ASSET_ACTOR_0_PROPERTY,
	KOMOREBI_ON_SCREEN_ASSET_ACTOR_NUM_PROPERTIES
};
static GParamSpec* komorebi_on_screen_asset_actor_properties[KOMOREBI_ON_SCREEN_ASSET_ACTOR_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _KomorebiOnScreenAssetActor {
	ClutterActor parent_instance;
	KomorebiOnScreenAssetActorPrivate * priv;
	guint assetAnimationTimeout;
};

struct _KomorebiOnScreenAssetActorClass {
	ClutterActorClass parent_class;
};

struct _KomorebiOnScreenAssetActorPrivate {
	KomorebiOnScreenBackgroundWindow* parent;
	ClutterImage* image;
	GdkPixbuf* pixbuf;
	gchar* cloudsDirection;
	gchar* fadeType;
};

static gint KomorebiOnScreenAssetActor_private_offset;
static gpointer komorebi_on_screen_asset_actor_parent_class = NULL;
VALA_EXTERN gboolean komorebi_utilities_assetVisible;
VALA_EXTERN gint komorebi_utilities_assetWidth;
VALA_EXTERN gint komorebi_utilities_screenWidth;
VALA_EXTERN gint komorebi_utilities_assetHeight;
VALA_EXTERN gint komorebi_utilities_screenHeight;
VALA_EXTERN gchar* komorebi_on_screen_wallpaperName;
VALA_EXTERN gint komorebi_utilities_assetMarginTop;
VALA_EXTERN gint komorebi_utilities_assetMarginRight;
VALA_EXTERN gint komorebi_utilities_assetMarginLeft;
VALA_EXTERN gint komorebi_utilities_assetMarginBottom;
VALA_EXTERN gint komorebi_utilities_assetAnimationSpeed;
VALA_EXTERN gchar* komorebi_utilities_assetAnimationMode;
VALA_EXTERN gchar* komorebi_utilities_wallpaperType;

VALA_EXTERN GType komorebi_on_screen_asset_actor_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KomorebiOnScreenAssetActor, g_object_unref)
VALA_EXTERN GType komorebi_on_screen_background_window_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KomorebiOnScreenBackgroundWindow, g_object_unref)
VALA_EXTERN KomorebiOnScreenAssetActor* komorebi_on_screen_asset_actor_new (KomorebiOnScreenBackgroundWindow* parent);
VALA_EXTERN KomorebiOnScreenAssetActor* komorebi_on_screen_asset_actor_construct (GType object_type,
                                                                      KomorebiOnScreenBackgroundWindow* parent);
VALA_EXTERN void komorebi_on_screen_asset_actor_setAsset (KomorebiOnScreenAssetActor* self);
VALA_EXTERN void komorebi_on_screen_asset_actor_fadeOut (KomorebiOnScreenAssetActor* self,
                                             gint custom_duration);
static void komorebi_on_screen_asset_actor_setMargins (KomorebiOnScreenAssetActor* self);
VALA_EXTERN gboolean komorebi_on_screen_asset_actor_shouldAnimate (KomorebiOnScreenAssetActor* self);
static void komorebi_on_screen_asset_actor_animate (KomorebiOnScreenAssetActor* self);
VALA_EXTERN void komorebi_on_screen_asset_actor_fadeIn (KomorebiOnScreenAssetActor* self,
                                            gint custom_duration);
static gboolean __lambda6_ (KomorebiOnScreenAssetActor* self);
static gboolean ___lambda6__gsource_func (gpointer self);
static void komorebi_on_screen_asset_actor_finalize (GObject * obj);
static GType komorebi_on_screen_asset_actor_get_type_once (void);

static inline gpointer
komorebi_on_screen_asset_actor_get_instance_private (KomorebiOnScreenAssetActor* self)
{
	return G_STRUCT_MEMBER_P (self, KomorebiOnScreenAssetActor_private_offset);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

KomorebiOnScreenAssetActor*
komorebi_on_screen_asset_actor_construct (GType object_type,
                                          KomorebiOnScreenBackgroundWindow* parent)
{
	KomorebiOnScreenAssetActor * self = NULL;
	KomorebiOnScreenBackgroundWindow* _tmp0_;
	ClutterImage* _tmp1_;
	g_return_val_if_fail (parent != NULL, NULL);
	self = (KomorebiOnScreenAssetActor*) g_object_new (object_type, NULL);
	_tmp0_ = _g_object_ref0 (parent);
	_g_object_unref0 (self->priv->parent);
	self->priv->parent = _tmp0_;
	_tmp1_ = self->priv->image;
	clutter_actor_set_content ((ClutterActor*) self, (ClutterContent*) _tmp1_);
	return self;
}

KomorebiOnScreenAssetActor*
komorebi_on_screen_asset_actor_new (KomorebiOnScreenBackgroundWindow* parent)
{
	return komorebi_on_screen_asset_actor_construct (KOMOREBI_ON_SCREEN_TYPE_ASSET_ACTOR, parent);
}

static const gchar*
string_to_string (const gchar* self)
{
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}

void
komorebi_on_screen_asset_actor_setAsset (KomorebiOnScreenAssetActor* self)
{
	gchar* assetPath = NULL;
	const gchar* _tmp10_;
	const gchar* _tmp11_;
	gchar* _tmp12_;
	const gchar* _tmp13_;
	GFile* _tmp14_;
	GFile* _tmp15_;
	gboolean _tmp16_;
	gboolean _tmp21_ = FALSE;
	CoglPixelFormat _tmp30_ = 0;
	GdkPixbuf* _tmp31_;
	gboolean _tmp32_;
	gboolean _tmp33_;
	ClutterImage* _tmp34_;
	GdkPixbuf* _tmp35_;
	guint8* _tmp36_;
	GdkPixbuf* _tmp37_;
	GdkPixbuf* _tmp38_;
	GdkPixbuf* _tmp39_;
	GError* _inner_error0_ = NULL;
	g_return_if_fail (self != NULL);
	if (!komorebi_utilities_assetVisible) {
		CoglPixelFormat _tmp0_ = 0;
		GdkPixbuf* _tmp1_;
		gboolean _tmp2_;
		gboolean _tmp3_;
		ClutterImage* _tmp4_;
		GdkPixbuf* _tmp5_;
		guint8* _tmp6_;
		GdkPixbuf* _tmp7_;
		GdkPixbuf* _tmp8_;
		GdkPixbuf* _tmp9_;
		_g_object_unref0 (self->priv->pixbuf);
		self->priv->pixbuf = NULL;
		_tmp1_ = self->priv->pixbuf;
		_tmp2_ = gdk_pixbuf_get_has_alpha (_tmp1_);
		_tmp3_ = _tmp2_;
		if (_tmp3_) {
			_tmp0_ = COGL_PIXEL_FORMAT_RGBA_8888;
		} else {
			_tmp0_ = COGL_PIXEL_FORMAT_RGB_888;
		}
		_tmp4_ = self->priv->image;
		_tmp5_ = self->priv->pixbuf;
		_tmp6_ = gdk_pixbuf_get_pixels (_tmp5_);
		_tmp7_ = self->priv->pixbuf;
		_tmp8_ = self->priv->pixbuf;
		_tmp9_ = self->priv->pixbuf;
		clutter_image_set_data (_tmp4_, _tmp6_, _tmp0_, (guint) gdk_pixbuf_get_width (_tmp7_), (guint) gdk_pixbuf_get_height (_tmp8_), (guint) gdk_pixbuf_get_rowstride (_tmp9_), &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return;
		}
		komorebi_on_screen_asset_actor_fadeOut (self, 90);
		return;
	}
	if (komorebi_utilities_assetWidth <= 0) {
		komorebi_utilities_assetWidth = komorebi_utilities_screenWidth;
	}
	if (komorebi_utilities_assetHeight <= 0) {
		komorebi_utilities_assetHeight = komorebi_utilities_screenHeight;
	}
	_tmp10_ = komorebi_on_screen_wallpaperName;
	_tmp11_ = string_to_string (_tmp10_);
	_tmp12_ = g_strconcat ("/System/Resources/Komorebi/", _tmp11_, "/assets.png", NULL);
	assetPath = _tmp12_;
	_tmp13_ = assetPath;
	_tmp14_ = g_file_new_for_path (_tmp13_);
	_tmp15_ = _tmp14_;
	_tmp16_ = !g_file_query_exists (_tmp15_, NULL);
	_g_object_unref0 (_tmp15_);
	if (_tmp16_) {
		const gchar* _tmp17_;
		const gchar* _tmp18_;
		gchar* _tmp19_;
		gchar* _tmp20_;
		_tmp17_ = assetPath;
		_tmp18_ = string_to_string (_tmp17_);
		_tmp19_ = g_strconcat ("[WARNING]: asset with path: ", _tmp18_, " does not exist\n", NULL);
		_tmp20_ = _tmp19_;
		g_print ("%s", _tmp20_);
		_g_free0 (_tmp20_);
		_g_free0 (assetPath);
		return;
	}
	if (komorebi_utilities_assetWidth != 0) {
		_tmp21_ = komorebi_utilities_assetHeight != 0;
	} else {
		_tmp21_ = FALSE;
	}
	if (_tmp21_) {
		GdkPixbuf* _tmp22_ = NULL;
		const gchar* _tmp23_;
		GdkPixbuf* _tmp24_;
		GdkPixbuf* _tmp25_;
		_tmp23_ = assetPath;
		_tmp24_ = gdk_pixbuf_new_from_file_at_scale (_tmp23_, komorebi_utilities_assetWidth, komorebi_utilities_assetHeight, FALSE, &_inner_error0_);
		_tmp22_ = _tmp24_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_free0 (assetPath);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return;
		}
		_tmp25_ = _tmp22_;
		_tmp22_ = NULL;
		_g_object_unref0 (self->priv->pixbuf);
		self->priv->pixbuf = _tmp25_;
		_g_object_unref0 (_tmp22_);
	} else {
		GdkPixbuf* _tmp26_ = NULL;
		const gchar* _tmp27_;
		GdkPixbuf* _tmp28_;
		GdkPixbuf* _tmp29_;
		_tmp27_ = assetPath;
		_tmp28_ = gdk_pixbuf_new_from_file (_tmp27_, &_inner_error0_);
		_tmp26_ = _tmp28_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_free0 (assetPath);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return;
		}
		_tmp29_ = _tmp26_;
		_tmp26_ = NULL;
		_g_object_unref0 (self->priv->pixbuf);
		self->priv->pixbuf = _tmp29_;
		_g_object_unref0 (_tmp26_);
	}
	_tmp31_ = self->priv->pixbuf;
	_tmp32_ = gdk_pixbuf_get_has_alpha (_tmp31_);
	_tmp33_ = _tmp32_;
	if (_tmp33_) {
		_tmp30_ = COGL_PIXEL_FORMAT_RGBA_8888;
	} else {
		_tmp30_ = COGL_PIXEL_FORMAT_RGB_888;
	}
	_tmp34_ = self->priv->image;
	_tmp35_ = self->priv->pixbuf;
	_tmp36_ = gdk_pixbuf_get_pixels (_tmp35_);
	_tmp37_ = self->priv->pixbuf;
	_tmp38_ = self->priv->pixbuf;
	_tmp39_ = self->priv->pixbuf;
	clutter_image_set_data (_tmp34_, _tmp36_, _tmp30_, (guint) gdk_pixbuf_get_width (_tmp37_), (guint) gdk_pixbuf_get_height (_tmp38_), (guint) gdk_pixbuf_get_rowstride (_tmp39_), &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (assetPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	clutter_actor_set_x ((ClutterActor*) self, (gfloat) 0);
	clutter_actor_set_y ((ClutterActor*) self, (gfloat) 0);
	clutter_actor_set_opacity ((ClutterActor*) self, (guint) 255);
	clutter_actor_remove_all_transitions ((ClutterActor*) self);
	komorebi_on_screen_asset_actor_setMargins (self);
	if (komorebi_on_screen_asset_actor_shouldAnimate (self)) {
		komorebi_on_screen_asset_actor_animate (self);
	} else {
		komorebi_on_screen_asset_actor_fadeIn (self, 90);
	}
	_g_free0 (assetPath);
}

static void
komorebi_on_screen_asset_actor_setMargins (KomorebiOnScreenAssetActor* self)
{
	gfloat _tmp0_;
	gfloat _tmp1_;
	gfloat _tmp2_;
	gfloat _tmp3_;
	gfloat _tmp4_;
	gfloat _tmp5_;
	gfloat _tmp6_;
	gfloat _tmp7_;
	g_return_if_fail (self != NULL);
	g_object_set ((ClutterActor*) self, "translation-y", (gfloat) 0, NULL);
	g_object_set ((ClutterActor*) self, "translation-x", (gfloat) 0, NULL);
	g_object_get ((ClutterActor*) self, "translation-y", &_tmp0_, NULL);
	_tmp1_ = _tmp0_;
	g_object_set ((ClutterActor*) self, "translation-y", _tmp1_ + komorebi_utilities_assetMarginTop, NULL);
	g_object_get ((ClutterActor*) self, "translation-x", &_tmp2_, NULL);
	_tmp3_ = _tmp2_;
	g_object_set ((ClutterActor*) self, "translation-x", _tmp3_ - komorebi_utilities_assetMarginRight, NULL);
	g_object_get ((ClutterActor*) self, "translation-x", &_tmp4_, NULL);
	_tmp5_ = _tmp4_;
	g_object_set ((ClutterActor*) self, "translation-x", _tmp5_ + komorebi_utilities_assetMarginLeft, NULL);
	g_object_get ((ClutterActor*) self, "translation-y", &_tmp6_, NULL);
	_tmp7_ = _tmp6_;
	g_object_set ((ClutterActor*) self, "translation-y", _tmp7_ - komorebi_utilities_assetMarginBottom, NULL);
}

static gboolean
__lambda6_ (KomorebiOnScreenAssetActor* self)
{
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	GQuark _tmp3_ = 0U;
	static GQuark _tmp2_label0 = 0;
	static GQuark _tmp2_label1 = 0;
	gboolean result;
	_tmp0_ = komorebi_utilities_assetAnimationMode;
	_tmp1_ = _tmp0_;
	_tmp3_ = (NULL == _tmp1_) ? 0 : g_quark_from_string (_tmp1_);
	if (_tmp3_ == ((0 != _tmp2_label0) ? _tmp2_label0 : (_tmp2_label0 = g_quark_from_static_string ("clouds")))) {
		switch (0) {
			default:
			{
				const gchar* _tmp4_;
				_tmp4_ = self->priv->cloudsDirection;
				if (g_strcmp0 (_tmp4_, "right") == 0) {
					gfloat _tmp5_;
					gfloat _tmp6_;
					gfloat _tmp7_;
					gfloat _tmp8_;
					_tmp5_ = clutter_actor_get_x ((ClutterActor*) self);
					_tmp6_ = _tmp5_;
					_tmp7_ = clutter_actor_get_width ((ClutterActor*) self);
					_tmp8_ = _tmp7_;
					if ((_tmp6_ + (_tmp8_ / 2)) >= ((gfloat) komorebi_utilities_screenWidth)) {
						gchar* _tmp9_;
						_tmp9_ = g_strdup ("left");
						_g_free0 (self->priv->cloudsDirection);
						self->priv->cloudsDirection = _tmp9_;
					} else {
						gfloat _tmp10_;
						gfloat _tmp11_;
						clutter_actor_save_easing_state ((ClutterActor*) self);
						clutter_actor_set_easing_duration ((ClutterActor*) self, (guint) (komorebi_utilities_assetAnimationSpeed * 100));
						_tmp10_ = clutter_actor_get_x ((ClutterActor*) self);
						_tmp11_ = _tmp10_;
						clutter_actor_set_x ((ClutterActor*) self, _tmp11_ + 60);
						clutter_actor_set_easing_mode ((ClutterActor*) self, CLUTTER_LINEAR);
						clutter_actor_restore_easing_state ((ClutterActor*) self);
					}
				} else {
					gfloat _tmp12_;
					gfloat _tmp13_;
					_tmp12_ = clutter_actor_get_x ((ClutterActor*) self);
					_tmp13_ = _tmp12_;
					if (_tmp13_ <= ((gfloat) 0)) {
						gchar* _tmp14_;
						_tmp14_ = g_strdup ("right");
						_g_free0 (self->priv->cloudsDirection);
						self->priv->cloudsDirection = _tmp14_;
					} else {
						gfloat _tmp15_;
						gfloat _tmp16_;
						clutter_actor_save_easing_state ((ClutterActor*) self);
						clutter_actor_set_easing_duration ((ClutterActor*) self, (guint) (komorebi_utilities_assetAnimationSpeed * 100));
						_tmp15_ = clutter_actor_get_x ((ClutterActor*) self);
						_tmp16_ = _tmp15_;
						clutter_actor_set_x ((ClutterActor*) self, _tmp16_ - 60);
						clutter_actor_set_easing_mode ((ClutterActor*) self, CLUTTER_LINEAR);
						clutter_actor_restore_easing_state ((ClutterActor*) self);
					}
				}
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label1) ? _tmp2_label1 : (_tmp2_label1 = g_quark_from_static_string ("light")))) {
		switch (0) {
			default:
			{
				const gchar* _tmp17_;
				_tmp17_ = self->priv->fadeType;
				if (g_strcmp0 (_tmp17_, "in") == 0) {
					gchar* _tmp18_;
					komorebi_on_screen_asset_actor_fadeIn (self, komorebi_utilities_assetAnimationSpeed * 100);
					_tmp18_ = g_strdup ("out");
					_g_free0 (self->priv->fadeType);
					self->priv->fadeType = _tmp18_;
				} else {
					gchar* _tmp19_;
					komorebi_on_screen_asset_actor_fadeOut (self, komorebi_utilities_assetAnimationSpeed * 100);
					_tmp19_ = g_strdup ("in");
					_g_free0 (self->priv->fadeType);
					self->priv->fadeType = _tmp19_;
				}
				break;
			}
		}
	}
	result = TRUE;
	return result;
}

static gboolean
___lambda6__gsource_func (gpointer self)
{
	gboolean result;
	result = __lambda6_ ((KomorebiOnScreenAssetActor*) self);
	return result;
}

static void
komorebi_on_screen_asset_actor_animate (KomorebiOnScreenAssetActor* self)
{
	g_return_if_fail (self != NULL);
	if (komorebi_utilities_assetAnimationSpeed <= 10) {
		komorebi_utilities_assetAnimationSpeed = 100;
		g_print ("[WARNING]: The Asset Animation Speed has been adjusted in this wallpap" \
"er. Please consider updating it to at least 100\n");
	}
	self->assetAnimationTimeout = g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) (komorebi_utilities_assetAnimationSpeed * 30), ___lambda6__gsource_func, g_object_ref (self), g_object_unref);
}

void
komorebi_on_screen_asset_actor_fadeIn (KomorebiOnScreenAssetActor* self,
                                       gint custom_duration)
{
	g_return_if_fail (self != NULL);
	clutter_actor_save_easing_state ((ClutterActor*) self);
	clutter_actor_set_easing_duration ((ClutterActor*) self, (guint) custom_duration);
	clutter_actor_set_opacity ((ClutterActor*) self, (guint) 255);
	clutter_actor_set_easing_mode ((ClutterActor*) self, CLUTTER_LINEAR);
	clutter_actor_restore_easing_state ((ClutterActor*) self);
}

void
komorebi_on_screen_asset_actor_fadeOut (KomorebiOnScreenAssetActor* self,
                                        gint custom_duration)
{
	g_return_if_fail (self != NULL);
	clutter_actor_save_easing_state ((ClutterActor*) self);
	clutter_actor_set_easing_duration ((ClutterActor*) self, (guint) custom_duration);
	clutter_actor_set_opacity ((ClutterActor*) self, (guint) 0);
	clutter_actor_set_easing_mode ((ClutterActor*) self, CLUTTER_LINEAR);
	clutter_actor_restore_easing_state ((ClutterActor*) self);
}

gboolean
komorebi_on_screen_asset_actor_shouldAnimate (KomorebiOnScreenAssetActor* self)
{
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	const gchar* _tmp2_;
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp2_ = komorebi_utilities_wallpaperType;
	if (g_strcmp0 (_tmp2_, "video") == 0) {
		_tmp1_ = TRUE;
	} else {
		const gchar* _tmp3_;
		_tmp3_ = komorebi_utilities_wallpaperType;
		_tmp1_ = g_strcmp0 (_tmp3_, "web_page") == 0;
	}
	if (_tmp1_) {
		_tmp0_ = TRUE;
	} else {
		const gchar* _tmp4_;
		_tmp4_ = komorebi_utilities_assetAnimationMode;
		_tmp0_ = g_strcmp0 (_tmp4_, "noanimation") == 0;
	}
	if (_tmp0_) {
		if (self->assetAnimationTimeout > ((guint) 0)) {
			g_source_remove (self->assetAnimationTimeout);
			self->assetAnimationTimeout = (guint) 0;
		}
		clutter_actor_remove_all_transitions ((ClutterActor*) self);
		komorebi_on_screen_asset_actor_fadeOut (self, 90);
		result = FALSE;
		return result;
	}
	result = TRUE;
	return result;
}

static void
komorebi_on_screen_asset_actor_class_init (KomorebiOnScreenAssetActorClass * klass,
                                           gpointer klass_data)
{
	komorebi_on_screen_asset_actor_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &KomorebiOnScreenAssetActor_private_offset);
	G_OBJECT_CLASS (klass)->finalize = komorebi_on_screen_asset_actor_finalize;
}

static void
komorebi_on_screen_asset_actor_instance_init (KomorebiOnScreenAssetActor * self,
                                              gpointer klass)
{
	ClutterImage* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	self->priv = komorebi_on_screen_asset_actor_get_instance_private (self);
	_tmp0_ = (ClutterImage*) clutter_image_new ();
	self->priv->image = _tmp0_;
	_tmp1_ = g_strdup ("right");
	self->priv->cloudsDirection = _tmp1_;
	_tmp2_ = g_strdup ("in");
	self->priv->fadeType = _tmp2_;
}

static void
komorebi_on_screen_asset_actor_finalize (GObject * obj)
{
	KomorebiOnScreenAssetActor * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, KOMOREBI_ON_SCREEN_TYPE_ASSET_ACTOR, KomorebiOnScreenAssetActor);
	_g_object_unref0 (self->priv->parent);
	_g_object_unref0 (self->priv->image);
	_g_object_unref0 (self->priv->pixbuf);
	_g_free0 (self->priv->cloudsDirection);
	_g_free0 (self->priv->fadeType);
	G_OBJECT_CLASS (komorebi_on_screen_asset_actor_parent_class)->finalize (obj);
}

static GType
komorebi_on_screen_asset_actor_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (KomorebiOnScreenAssetActorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) komorebi_on_screen_asset_actor_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (KomorebiOnScreenAssetActor), 0, (GInstanceInitFunc) komorebi_on_screen_asset_actor_instance_init, NULL };
	GType komorebi_on_screen_asset_actor_type_id;
	komorebi_on_screen_asset_actor_type_id = g_type_register_static (clutter_actor_get_type (), "KomorebiOnScreenAssetActor", &g_define_type_info, 0);
	KomorebiOnScreenAssetActor_private_offset = g_type_add_instance_private (komorebi_on_screen_asset_actor_type_id, sizeof (KomorebiOnScreenAssetActorPrivate));
	return komorebi_on_screen_asset_actor_type_id;
}

GType
komorebi_on_screen_asset_actor_get_type (void)
{
	static volatile gsize komorebi_on_screen_asset_actor_type_id__once = 0;
	if (g_once_init_enter (&komorebi_on_screen_asset_actor_type_id__once)) {
		GType komorebi_on_screen_asset_actor_type_id;
		komorebi_on_screen_asset_actor_type_id = komorebi_on_screen_asset_actor_get_type_once ();
		g_once_init_leave (&komorebi_on_screen_asset_actor_type_id__once, komorebi_on_screen_asset_actor_type_id);
	}
	return komorebi_on_screen_asset_actor_type_id__once;
}

