/* BackgroundWindow.c generated by valac 0.56.13, the Vala compiler
 * generated from BackgroundWindow.vala, do not modify */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gtk/gtk.h>
#include <glib-object.h>
#include <webkit2/webkit2.h>
#include <clutter-gtk/clutter-gtk.h>
#include <clutter/clutter.h>
#include <clutter-gst/clutter-gst.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <float.h>
#include <math.h>
#include <gdk/gdk.h>
#include <cairo-gobject.h>
#include <cogl/cogl.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define KOMOREBI_ON_SCREEN_TYPE_BACKGROUND_WINDOW (komorebi_on_screen_background_window_get_type ())
#define KOMOREBI_ON_SCREEN_BACKGROUND_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KOMOREBI_ON_SCREEN_TYPE_BACKGROUND_WINDOW, KomorebiOnScreenBackgroundWindow))
#define KOMOREBI_ON_SCREEN_BACKGROUND_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KOMOREBI_ON_SCREEN_TYPE_BACKGROUND_WINDOW, KomorebiOnScreenBackgroundWindowClass))
#define KOMOREBI_ON_SCREEN_IS_BACKGROUND_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KOMOREBI_ON_SCREEN_TYPE_BACKGROUND_WINDOW))
#define KOMOREBI_ON_SCREEN_IS_BACKGROUND_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KOMOREBI_ON_SCREEN_TYPE_BACKGROUND_WINDOW))
#define KOMOREBI_ON_SCREEN_BACKGROUND_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KOMOREBI_ON_SCREEN_TYPE_BACKGROUND_WINDOW, KomorebiOnScreenBackgroundWindowClass))

typedef struct _KomorebiOnScreenBackgroundWindow KomorebiOnScreenBackgroundWindow;
typedef struct _KomorebiOnScreenBackgroundWindowClass KomorebiOnScreenBackgroundWindowClass;
typedef struct _KomorebiOnScreenBackgroundWindowPrivate KomorebiOnScreenBackgroundWindowPrivate;

#define KOMOREBI_ON_SCREEN_TYPE_DATE_TIME_BOX (komorebi_on_screen_date_time_box_get_type ())
#define KOMOREBI_ON_SCREEN_DATE_TIME_BOX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KOMOREBI_ON_SCREEN_TYPE_DATE_TIME_BOX, KomorebiOnScreenDateTimeBox))
#define KOMOREBI_ON_SCREEN_DATE_TIME_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KOMOREBI_ON_SCREEN_TYPE_DATE_TIME_BOX, KomorebiOnScreenDateTimeBoxClass))
#define KOMOREBI_ON_SCREEN_IS_DATE_TIME_BOX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KOMOREBI_ON_SCREEN_TYPE_DATE_TIME_BOX))
#define KOMOREBI_ON_SCREEN_IS_DATE_TIME_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KOMOREBI_ON_SCREEN_TYPE_DATE_TIME_BOX))
#define KOMOREBI_ON_SCREEN_DATE_TIME_BOX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KOMOREBI_ON_SCREEN_TYPE_DATE_TIME_BOX, KomorebiOnScreenDateTimeBoxClass))

typedef struct _KomorebiOnScreenDateTimeBox KomorebiOnScreenDateTimeBox;
typedef struct _KomorebiOnScreenDateTimeBoxClass KomorebiOnScreenDateTimeBoxClass;

#define KOMOREBI_ON_SCREEN_TYPE_ASSET_ACTOR (komorebi_on_screen_asset_actor_get_type ())
#define KOMOREBI_ON_SCREEN_ASSET_ACTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KOMOREBI_ON_SCREEN_TYPE_ASSET_ACTOR, KomorebiOnScreenAssetActor))
#define KOMOREBI_ON_SCREEN_ASSET_ACTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KOMOREBI_ON_SCREEN_TYPE_ASSET_ACTOR, KomorebiOnScreenAssetActorClass))
#define KOMOREBI_ON_SCREEN_IS_ASSET_ACTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KOMOREBI_ON_SCREEN_TYPE_ASSET_ACTOR))
#define KOMOREBI_ON_SCREEN_IS_ASSET_ACTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KOMOREBI_ON_SCREEN_TYPE_ASSET_ACTOR))
#define KOMOREBI_ON_SCREEN_ASSET_ACTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KOMOREBI_ON_SCREEN_TYPE_ASSET_ACTOR, KomorebiOnScreenAssetActorClass))

typedef struct _KomorebiOnScreenAssetActor KomorebiOnScreenAssetActor;
typedef struct _KomorebiOnScreenAssetActorClass KomorebiOnScreenAssetActorClass;
enum  {
	KOMOREBI_ON_SCREEN_BACKGROUND_WINDOW_0_PROPERTY,
	KOMOREBI_ON_SCREEN_BACKGROUND_WINDOW_MAIN_ACTOR_PROPERTY,
	KOMOREBI_ON_SCREEN_BACKGROUND_WINDOW_NUM_PROPERTIES
};
static GParamSpec* komorebi_on_screen_background_window_properties[KOMOREBI_ON_SCREEN_BACKGROUND_WINDOW_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))

struct _KomorebiOnScreenBackgroundWindow {
	GtkWindow parent_instance;
	KomorebiOnScreenBackgroundWindowPrivate * priv;
};

struct _KomorebiOnScreenBackgroundWindowClass {
	GtkWindowClass parent_class;
};

struct _KomorebiOnScreenBackgroundWindowPrivate {
	WebKitWebView* webView;
	GtkClutterActor* webViewActor;
	GtkClutterEmbed* embed;
	ClutterActor* _mainActor;
	ClutterGstPlayback* videoPlayback;
	ClutterGstContent* videoContent;
	ClutterActor* wallpaperActor;
	GdkPixbuf* wallpaperPixbuf;
	ClutterImage* wallpaperImage;
	KomorebiOnScreenDateTimeBox* dateTimeBox;
	KomorebiOnScreenAssetActor* assetActor;
	gboolean dateTimeBoxParallax;
};

VALA_EXTERN gchar* komorebi_on_screen_wallpaperName;
gchar* komorebi_on_screen_wallpaperName = NULL;
static gint KomorebiOnScreenBackgroundWindow_private_offset;
static gpointer komorebi_on_screen_background_window_parent_class = NULL;
VALA_EXTERN gint komorebi_utilities_screenWidth;
VALA_EXTERN gint komorebi_utilities_screenHeight;
VALA_EXTERN gchar* komorebi_utilities_desktopPath;
VALA_EXTERN gboolean komorebi_utilities_dateTimeVisible;
VALA_EXTERN gchar* komorebi_utilities_wallpaperType;
VALA_EXTERN gboolean komorebi_utilities_dateTimeAlwaysOnTop;
VALA_EXTERN gboolean komorebi_utilities_assetVisible;
VALA_EXTERN gboolean komorebi_utilities_wallpaperParallax;
VALA_EXTERN gchar* komorebi_utilities_videoFileName;
VALA_EXTERN gchar* komorebi_utilities_webPageUrl;

VALA_EXTERN GType komorebi_on_screen_background_window_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KomorebiOnScreenBackgroundWindow, g_object_unref)
VALA_EXTERN GType komorebi_on_screen_date_time_box_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KomorebiOnScreenDateTimeBox, g_object_unref)
VALA_EXTERN GType komorebi_on_screen_asset_actor_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KomorebiOnScreenAssetActor, g_object_unref)
VALA_EXTERN KomorebiOnScreenBackgroundWindow* komorebi_on_screen_background_window_new (gint monitorIndex);
VALA_EXTERN KomorebiOnScreenBackgroundWindow* komorebi_on_screen_background_window_construct (GType object_type,
                                                                                  gint monitorIndex);
static void komorebi_on_screen_background_window_getMonitorSize (KomorebiOnScreenBackgroundWindow* self,
                                                          gint monitorIndex);
static void komorebi_on_screen_background_window_set_mainActor (KomorebiOnScreenBackgroundWindow* self,
                                                         ClutterActor* value);
VALA_EXTERN KomorebiOnScreenAssetActor* komorebi_on_screen_asset_actor_new (KomorebiOnScreenBackgroundWindow* parent);
VALA_EXTERN KomorebiOnScreenAssetActor* komorebi_on_screen_asset_actor_construct (GType object_type,
                                                                      KomorebiOnScreenBackgroundWindow* parent);
VALA_EXTERN KomorebiOnScreenDateTimeBox* komorebi_on_screen_date_time_box_new (KomorebiOnScreenBackgroundWindow* parent);
VALA_EXTERN KomorebiOnScreenDateTimeBox* komorebi_on_screen_date_time_box_construct (GType object_type,
                                                                         KomorebiOnScreenBackgroundWindow* parent);
static void __lambda7_ (KomorebiOnScreenBackgroundWindow* self);
static void ___lambda7__g_object_notify (GObject* _sender,
                                  GParamSpec* pspec,
                                  gpointer self);
VALA_EXTERN ClutterActor* komorebi_on_screen_background_window_get_mainActor (KomorebiOnScreenBackgroundWindow* self);
VALA_EXTERN void komorebi_on_screen_background_window_initializeConfigFile (KomorebiOnScreenBackgroundWindow* self);
static void komorebi_on_screen_background_window_setWallpaper (KomorebiOnScreenBackgroundWindow* self);
VALA_EXTERN void komorebi_on_screen_date_time_box_setDateTime (KomorebiOnScreenDateTimeBox* self);
VALA_EXTERN void komorebi_on_screen_date_time_box_fadeOut (KomorebiOnScreenDateTimeBox* self);
VALA_EXTERN void komorebi_on_screen_asset_actor_setAsset (KomorebiOnScreenAssetActor* self);
VALA_EXTERN gboolean komorebi_on_screen_asset_actor_shouldAnimate (KomorebiOnScreenAssetActor* self);
VALA_EXTERN void komorebi_on_screen_background_window_wallpaperFromUrl (KomorebiOnScreenBackgroundWindow* self,
                                                            gchar* url);
VALA_EXTERN void komorebi_on_screen_background_window_fadeIn (KomorebiOnScreenBackgroundWindow* self);
VALA_EXTERN void komorebi_on_screen_date_time_box_setPosition (KomorebiOnScreenDateTimeBox* self);
VALA_EXTERN gboolean komorebi_on_screen_background_window_contains_point (KomorebiOnScreenBackgroundWindow* self,
                                                              gint x,
                                                              gint y);
static void komorebi_on_screen_background_window_finalize (GObject * obj);
static GType komorebi_on_screen_background_window_get_type_once (void);
static void _vala_komorebi_on_screen_background_window_get_property (GObject * object,
                                                              guint property_id,
                                                              GValue * value,
                                                              GParamSpec * pspec);
static void _vala_komorebi_on_screen_background_window_set_property (GObject * object,
                                                              guint property_id,
                                                              const GValue * value,
                                                              GParamSpec * pspec);

static inline gpointer
komorebi_on_screen_background_window_get_instance_private (KomorebiOnScreenBackgroundWindow* self)
{
	return G_STRUCT_MEMBER_P (self, KomorebiOnScreenBackgroundWindow_private_offset);
}

static void
__lambda7_ (KomorebiOnScreenBackgroundWindow* self)
{
	gboolean _tmp0_ = FALSE;
	ClutterGstPlayback* _tmp1_;
	gdouble _tmp2_;
	gdouble _tmp3_;
	_tmp1_ = self->priv->videoPlayback;
	_tmp2_ = clutter_gst_playback_get_progress (_tmp1_);
	_tmp3_ = _tmp2_;
	if (_tmp3_ >= 1.0) {
		const gchar* _tmp4_;
		_tmp4_ = komorebi_utilities_wallpaperType;
		_tmp0_ = g_strcmp0 (_tmp4_, "video") == 0;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		ClutterGstPlayback* _tmp5_;
		ClutterGstPlayback* _tmp6_;
		_tmp5_ = self->priv->videoPlayback;
		clutter_gst_playback_set_progress (_tmp5_, 0.0);
		_tmp6_ = self->priv->videoPlayback;
		clutter_gst_player_set_playing ((ClutterGstPlayer*) _tmp6_, TRUE);
	}
}

static void
___lambda7__g_object_notify (GObject* _sender,
                             GParamSpec* pspec,
                             gpointer self)
{
	__lambda7_ ((KomorebiOnScreenBackgroundWindow*) self);
}

KomorebiOnScreenBackgroundWindow*
komorebi_on_screen_background_window_construct (GType object_type,
                                                gint monitorIndex)
{
	KomorebiOnScreenBackgroundWindow * self = NULL;
	GtkClutterEmbed* _tmp0_ = NULL;
	GtkClutterEmbed* _tmp1_;
	ClutterActor* _tmp2_;
	const gchar* _tmp3_;
	gchar* _tmp4_;
	KomorebiOnScreenAssetActor* _tmp5_;
	const gchar* _tmp7_;
	ClutterGstPlayback* _tmp10_;
	ClutterGstContent* _tmp11_;
	ClutterGstPlayback* _tmp12_;
	ClutterGstContent* _tmp13_;
	ClutterGstPlayback* _tmp14_;
	ClutterGstPlayback* _tmp15_;
	ClutterGstPlayback* _tmp16_;
	ClutterActor* _tmp17_;
	ClutterColor _tmp18_ = {0};
	GtkClutterActor* _tmp19_;
	ClutterActor* _tmp20_;
	KomorebiOnScreenAssetActor* _tmp21_;
	ClutterActor* _tmp22_;
	ClutterActor* _tmp23_;
	ClutterActor* _tmp24_;
	ClutterActor* _tmp25_;
	KomorebiOnScreenDateTimeBox* _tmp26_;
	ClutterActor* _tmp27_;
	KomorebiOnScreenAssetActor* _tmp28_;
	GtkClutterEmbed* _tmp29_;
	self = (KomorebiOnScreenBackgroundWindow*) g_object_new (object_type, NULL);
	gtk_window_set_title ((GtkWindow*) self, "Desktop");
	komorebi_on_screen_background_window_getMonitorSize (self, monitorIndex);
	_tmp0_ = (GtkClutterEmbed*) gtk_clutter_embed_new ();
	g_object_set ((GtkWidget*) _tmp0_, "width-request", komorebi_utilities_screenWidth, NULL);
	g_object_set ((GtkWidget*) _tmp0_, "height-request", komorebi_utilities_screenHeight, NULL);
	g_object_ref_sink (_tmp0_);
	_g_object_unref0 (self->priv->embed);
	self->priv->embed = _tmp0_;
	_tmp1_ = self->priv->embed;
	_tmp2_ = gtk_clutter_embed_get_stage (_tmp1_);
	komorebi_on_screen_background_window_set_mainActor (self, _tmp2_);
	_tmp3_ = g_get_user_special_dir (G_USER_DIRECTORY_DESKTOP);
	_tmp4_ = g_strdup (_tmp3_);
	_g_free0 (komorebi_utilities_desktopPath);
	komorebi_utilities_desktopPath = _tmp4_;
	_tmp5_ = komorebi_on_screen_asset_actor_new (self);
	g_object_ref_sink (_tmp5_);
	_g_object_unref0 (self->priv->assetActor);
	self->priv->assetActor = _tmp5_;
	if (komorebi_utilities_dateTimeVisible) {
		KomorebiOnScreenDateTimeBox* _tmp6_;
		_tmp6_ = komorebi_on_screen_date_time_box_new (self);
		g_object_ref_sink (_tmp6_);
		_g_object_unref0 (self->priv->dateTimeBox);
		self->priv->dateTimeBox = _tmp6_;
	} else {
		_g_object_unref0 (self->priv->dateTimeBox);
		self->priv->dateTimeBox = NULL;
	}
	_tmp7_ = komorebi_utilities_wallpaperType;
	if (g_strcmp0 (_tmp7_, "web_page") == 0) {
		WebKitWebView* _tmp8_;
		GtkClutterActor* _tmp9_;
		_tmp8_ = self->priv->webView;
		_tmp9_ = (GtkClutterActor*) gtk_clutter_actor_new_with_contents ((GtkWidget*) _tmp8_);
		g_object_ref_sink (_tmp9_);
		_g_object_unref0 (self->priv->webViewActor);
		self->priv->webViewActor = _tmp9_;
	} else {
		_g_object_unref0 (self->priv->webViewActor);
		self->priv->webViewActor = NULL;
	}
	_tmp10_ = clutter_gst_playback_new ();
	_g_object_unref0 (self->priv->videoPlayback);
	self->priv->videoPlayback = _tmp10_;
	_tmp11_ = (ClutterGstContent*) clutter_gst_content_new ();
	_g_object_unref0 (self->priv->videoContent);
	self->priv->videoContent = _tmp11_;
	_tmp12_ = self->priv->videoPlayback;
	clutter_gst_playback_set_seek_flags (_tmp12_, CLUTTER_GST_SEEK_FLAG_ACCURATE);
	_tmp13_ = self->priv->videoContent;
	_tmp14_ = self->priv->videoPlayback;
	clutter_gst_content_set_player (_tmp13_, (GObject*) _tmp14_);
	_tmp15_ = self->priv->videoPlayback;
	clutter_gst_player_set_audio_volume ((ClutterGstPlayer*) _tmp15_, 0.0);
	_tmp16_ = self->priv->videoPlayback;
	g_signal_connect_object ((GObject*) _tmp16_, "notify::progress", (GCallback) ___lambda7__g_object_notify, self, 0);
	gtk_widget_set_size_request ((GtkWidget*) self, komorebi_utilities_screenWidth, komorebi_utilities_screenHeight);
	gtk_window_set_resizable ((GtkWindow*) self, FALSE);
	gtk_window_set_type_hint ((GtkWindow*) self, GDK_WINDOW_TYPE_HINT_DESKTOP);
	gtk_window_set_keep_below ((GtkWindow*) self, TRUE);
	gtk_widget_set_app_paintable ((GtkWidget*) self, FALSE);
	gtk_window_set_skip_pager_hint ((GtkWindow*) self, TRUE);
	gtk_window_set_skip_taskbar_hint ((GtkWindow*) self, TRUE);
	gtk_window_set_accept_focus ((GtkWindow*) self, TRUE);
	gtk_window_stick ((GtkWindow*) self);
	gtk_window_set_decorated ((GtkWindow*) self, FALSE);
	_tmp17_ = self->priv->_mainActor;
	clutter_color_from_string (&_tmp18_, "black");
	clutter_actor_set_background_color (_tmp17_, &_tmp18_);
	_tmp19_ = self->priv->webViewActor;
	clutter_actor_set_size ((ClutterActor*) _tmp19_, (gfloat) komorebi_utilities_screenWidth, (gfloat) komorebi_utilities_screenHeight);
	_tmp20_ = self->priv->wallpaperActor;
	clutter_actor_set_size (_tmp20_, (gfloat) komorebi_utilities_screenWidth, (gfloat) komorebi_utilities_screenHeight);
	_tmp21_ = self->priv->assetActor;
	clutter_actor_set_size ((ClutterActor*) _tmp21_, (gfloat) komorebi_utilities_screenWidth, (gfloat) komorebi_utilities_screenHeight);
	_tmp22_ = self->priv->wallpaperActor;
	clutter_actor_set_pivot_point (_tmp22_, 0.5f, 0.5f);
	_tmp23_ = self->priv->_mainActor;
	_tmp24_ = self->priv->wallpaperActor;
	clutter_actor_add_child (_tmp23_, _tmp24_);
	_tmp25_ = self->priv->_mainActor;
	_tmp26_ = self->priv->dateTimeBox;
	clutter_actor_add_child (_tmp25_, (ClutterActor*) _tmp26_);
	_tmp27_ = self->priv->_mainActor;
	_tmp28_ = self->priv->assetActor;
	clutter_actor_add_child (_tmp27_, (ClutterActor*) _tmp28_);
	_tmp29_ = self->priv->embed;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp29_);
	komorebi_on_screen_background_window_initializeConfigFile (self);
	return self;
}

KomorebiOnScreenBackgroundWindow*
komorebi_on_screen_background_window_new (gint monitorIndex)
{
	return komorebi_on_screen_background_window_construct (KOMOREBI_ON_SCREEN_TYPE_BACKGROUND_WINDOW, monitorIndex);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

static void
komorebi_on_screen_background_window_getMonitorSize (KomorebiOnScreenBackgroundWindow* self,
                                                     gint monitorIndex)
{
	GdkRectangle rectangle = {0};
	GdkScreen* screen = NULL;
	GdkScreen* _tmp0_;
	GdkScreen* _tmp1_;
	GdkRectangle _tmp2_ = {0};
	GdkRectangle _tmp3_;
	GdkRectangle _tmp4_;
	GdkRectangle _tmp5_;
	GdkRectangle _tmp6_;
	g_return_if_fail (self != NULL);
	_tmp0_ = gdk_screen_get_default ();
	_tmp1_ = _g_object_ref0 (_tmp0_);
	screen = _tmp1_;
	gdk_screen_get_monitor_geometry (screen, monitorIndex, &_tmp2_);
	rectangle = _tmp2_;
	_tmp3_ = rectangle;
	komorebi_utilities_screenHeight = _tmp3_.height;
	_tmp4_ = rectangle;
	komorebi_utilities_screenWidth = _tmp4_.width;
	_tmp5_ = rectangle;
	_tmp6_ = rectangle;
	gtk_window_move ((GtkWindow*) self, _tmp5_.x, _tmp6_.y);
	_g_object_unref0 (screen);
}

void
komorebi_on_screen_background_window_initializeConfigFile (KomorebiOnScreenBackgroundWindow* self)
{
	gboolean _tmp8_ = FALSE;
	gboolean _tmp9_ = FALSE;
	const gchar* _tmp10_;
	g_return_if_fail (self != NULL);
	komorebi_on_screen_background_window_setWallpaper (self);
	if (komorebi_utilities_dateTimeVisible) {
		KomorebiOnScreenDateTimeBox* _tmp6_;
		if (komorebi_utilities_dateTimeAlwaysOnTop) {
			ClutterActor* _tmp0_;
			KomorebiOnScreenDateTimeBox* _tmp1_;
			KomorebiOnScreenAssetActor* _tmp2_;
			_tmp0_ = self->priv->_mainActor;
			_tmp1_ = self->priv->dateTimeBox;
			_tmp2_ = self->priv->assetActor;
			clutter_actor_set_child_above_sibling (_tmp0_, (ClutterActor*) _tmp1_, (ClutterActor*) _tmp2_);
		} else {
			ClutterActor* _tmp3_;
			KomorebiOnScreenDateTimeBox* _tmp4_;
			KomorebiOnScreenAssetActor* _tmp5_;
			_tmp3_ = self->priv->_mainActor;
			_tmp4_ = self->priv->dateTimeBox;
			_tmp5_ = self->priv->assetActor;
			clutter_actor_set_child_below_sibling (_tmp3_, (ClutterActor*) _tmp4_, (ClutterActor*) _tmp5_);
		}
		_tmp6_ = self->priv->dateTimeBox;
		komorebi_on_screen_date_time_box_setDateTime (_tmp6_);
	} else {
		KomorebiOnScreenDateTimeBox* _tmp7_;
		_tmp7_ = self->priv->dateTimeBox;
		komorebi_on_screen_date_time_box_fadeOut (_tmp7_);
	}
	_tmp10_ = komorebi_utilities_wallpaperType;
	if (g_strcmp0 (_tmp10_, "video") != 0) {
		const gchar* _tmp11_;
		_tmp11_ = komorebi_utilities_wallpaperType;
		_tmp9_ = g_strcmp0 (_tmp11_, "web_page") != 0;
	} else {
		_tmp9_ = FALSE;
	}
	if (_tmp9_) {
		_tmp8_ = komorebi_utilities_assetVisible;
	} else {
		_tmp8_ = FALSE;
	}
	if (_tmp8_) {
		KomorebiOnScreenAssetActor* _tmp12_;
		_tmp12_ = self->priv->assetActor;
		komorebi_on_screen_asset_actor_setAsset (_tmp12_);
	} else {
		KomorebiOnScreenAssetActor* _tmp13_;
		_tmp13_ = self->priv->assetActor;
		komorebi_on_screen_asset_actor_shouldAnimate (_tmp13_);
	}
}

static const gchar*
string_to_string (const gchar* self)
{
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}

static void
komorebi_on_screen_background_window_setWallpaper (KomorebiOnScreenBackgroundWindow* self)
{
	gint scaleWidth = 0;
	gint scaleHeight = 0;
	const gchar* _tmp4_;
	const gchar* _tmp17_;
	ClutterActor* _tmp31_;
	ClutterImage* _tmp32_;
	GdkPixbuf* _tmp33_ = NULL;
	const gchar* _tmp34_;
	const gchar* _tmp35_;
	gchar* _tmp36_;
	gchar* _tmp37_;
	GdkPixbuf* _tmp38_;
	GdkPixbuf* _tmp39_;
	GdkPixbuf* _tmp40_;
	ClutterImage* _tmp41_;
	GdkPixbuf* _tmp42_;
	guint8* _tmp43_;
	GdkPixbuf* _tmp44_;
	GdkPixbuf* _tmp45_;
	GdkPixbuf* _tmp46_;
	GError* _inner_error0_ = NULL;
	g_return_if_fail (self != NULL);
	scaleWidth = komorebi_utilities_screenWidth;
	scaleHeight = komorebi_utilities_screenHeight;
	if (komorebi_utilities_wallpaperParallax) {
		ClutterActor* _tmp0_;
		ClutterActor* _tmp1_;
		_tmp0_ = self->priv->wallpaperActor;
		g_object_set (_tmp0_, "scale-y", (gdouble) 1.05f, NULL);
		_tmp1_ = self->priv->wallpaperActor;
		g_object_set (_tmp1_, "scale-x", (gdouble) 1.05f, NULL);
	} else {
		ClutterActor* _tmp2_;
		ClutterActor* _tmp3_;
		_tmp2_ = self->priv->wallpaperActor;
		g_object_set (_tmp2_, "scale-y", (gdouble) 1.00f, NULL);
		_tmp3_ = self->priv->wallpaperActor;
		g_object_set (_tmp3_, "scale-x", (gdouble) 1.00f, NULL);
	}
	_tmp4_ = komorebi_utilities_wallpaperType;
	if (g_strcmp0 (_tmp4_, "video") == 0) {
		gchar* videoPath = NULL;
		const gchar* _tmp5_;
		const gchar* _tmp6_;
		const gchar* _tmp7_;
		const gchar* _tmp8_;
		gchar* _tmp9_;
		ClutterGstPlayback* _tmp10_;
		const gchar* _tmp11_;
		ClutterGstPlayback* _tmp12_;
		ClutterActor* _tmp13_;
		ClutterGstContent* _tmp14_;
		_tmp5_ = komorebi_on_screen_wallpaperName;
		_tmp6_ = string_to_string (_tmp5_);
		_tmp7_ = komorebi_utilities_videoFileName;
		_tmp8_ = string_to_string (_tmp7_);
		_tmp9_ = g_strconcat ("file:///System/Resources/Komorebi/", _tmp6_, "/", _tmp8_, NULL);
		videoPath = _tmp9_;
		_tmp10_ = self->priv->videoPlayback;
		_tmp11_ = videoPath;
		clutter_gst_playback_set_uri (_tmp10_, _tmp11_);
		_tmp12_ = self->priv->videoPlayback;
		clutter_gst_player_set_playing ((ClutterGstPlayer*) _tmp12_, TRUE);
		_tmp13_ = self->priv->wallpaperActor;
		_tmp14_ = self->priv->videoContent;
		clutter_actor_set_content (_tmp13_, (ClutterContent*) _tmp14_);
		_g_free0 (videoPath);
		return;
	} else {
		ClutterGstPlayback* _tmp15_;
		ClutterGstPlayback* _tmp16_;
		_tmp15_ = self->priv->videoPlayback;
		clutter_gst_player_set_playing ((ClutterGstPlayer*) _tmp15_, FALSE);
		_tmp16_ = self->priv->videoPlayback;
		clutter_gst_playback_set_uri (_tmp16_, "");
	}
	_tmp17_ = komorebi_utilities_wallpaperType;
	if (g_strcmp0 (_tmp17_, "web_page") == 0) {
		const gchar* _tmp18_;
		gchar* _tmp19_;
		ClutterActor* _tmp20_;
		GtkClutterActor* _tmp21_;
		ClutterActor* _tmp22_;
		ClutterActor* _tmp23_;
		_tmp18_ = komorebi_utilities_webPageUrl;
		_tmp19_ = g_strdup (_tmp18_);
		komorebi_on_screen_background_window_wallpaperFromUrl (self, _tmp19_);
		_tmp20_ = self->priv->wallpaperActor;
		clutter_actor_set_content (_tmp20_, NULL);
		_g_object_unref0 (self->priv->wallpaperPixbuf);
		self->priv->wallpaperPixbuf = NULL;
		_tmp21_ = self->priv->webViewActor;
		_tmp22_ = clutter_actor_get_parent ((ClutterActor*) _tmp21_);
		_tmp23_ = self->priv->wallpaperActor;
		if (_tmp22_ != _tmp23_) {
			ClutterActor* _tmp24_;
			GtkClutterActor* _tmp25_;
			_tmp24_ = self->priv->wallpaperActor;
			_tmp25_ = self->priv->webViewActor;
			clutter_actor_add_child (_tmp24_, (ClutterActor*) _tmp25_);
		}
		return;
	} else {
		GtkClutterActor* _tmp26_;
		ClutterActor* _tmp27_;
		ClutterActor* _tmp28_;
		_tmp26_ = self->priv->webViewActor;
		_tmp27_ = clutter_actor_get_parent ((ClutterActor*) _tmp26_);
		_tmp28_ = self->priv->wallpaperActor;
		if (_tmp27_ == _tmp28_) {
			ClutterActor* _tmp29_;
			GtkClutterActor* _tmp30_;
			_tmp29_ = self->priv->wallpaperActor;
			_tmp30_ = self->priv->webViewActor;
			clutter_actor_remove_child (_tmp29_, (ClutterActor*) _tmp30_);
		}
	}
	_tmp31_ = self->priv->wallpaperActor;
	_tmp32_ = self->priv->wallpaperImage;
	clutter_actor_set_content (_tmp31_, (ClutterContent*) _tmp32_);
	_tmp34_ = komorebi_on_screen_wallpaperName;
	_tmp35_ = string_to_string (_tmp34_);
	_tmp36_ = g_strconcat ("/System/Resources/Komorebi/", _tmp35_, "/wallpaper.jpg", NULL);
	_tmp37_ = _tmp36_;
	_tmp38_ = gdk_pixbuf_new_from_file_at_scale (_tmp37_, scaleWidth, scaleHeight, FALSE, &_inner_error0_);
	_tmp39_ = _tmp38_;
	_g_free0 (_tmp37_);
	_tmp33_ = _tmp39_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_tmp40_ = _tmp33_;
	_tmp33_ = NULL;
	_g_object_unref0 (self->priv->wallpaperPixbuf);
	self->priv->wallpaperPixbuf = _tmp40_;
	_tmp41_ = self->priv->wallpaperImage;
	_tmp42_ = self->priv->wallpaperPixbuf;
	_tmp43_ = gdk_pixbuf_get_pixels (_tmp42_);
	_tmp44_ = self->priv->wallpaperPixbuf;
	_tmp45_ = self->priv->wallpaperPixbuf;
	_tmp46_ = self->priv->wallpaperPixbuf;
	clutter_image_set_data (_tmp41_, _tmp43_, COGL_PIXEL_FORMAT_RGB_888, (guint) gdk_pixbuf_get_width (_tmp44_), (guint) gdk_pixbuf_get_height (_tmp45_), (guint) gdk_pixbuf_get_rowstride (_tmp46_), &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_object_unref0 (_tmp33_);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_g_object_unref0 (_tmp33_);
}

static gchar*
string_replace (const gchar* self,
                const gchar* old,
                const gchar* replacement)
{
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	GError* _inner_error0_ = NULL;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	if ((*((gchar*) self)) == '\0') {
		_tmp1_ = TRUE;
	} else {
		_tmp1_ = (*((gchar*) old)) == '\0';
	}
	if (_tmp1_) {
		_tmp0_ = TRUE;
	} else {
		_tmp0_ = g_strcmp0 (old, replacement) == 0;
	}
	if (_tmp0_) {
		gchar* _tmp2_;
		_tmp2_ = g_strdup (self);
		result = _tmp2_;
		return result;
	}
	{
		GRegex* regex = NULL;
		gchar* _tmp3_;
		gchar* _tmp4_;
		GRegex* _tmp5_;
		GRegex* _tmp6_;
		gchar* _tmp7_ = NULL;
		GRegex* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
		_tmp3_ = g_regex_escape_string (old, -1);
		_tmp4_ = _tmp3_;
		_tmp5_ = g_regex_new (_tmp4_, 0, 0, &_inner_error0_);
		_tmp6_ = _tmp5_;
		_g_free0 (_tmp4_);
		regex = _tmp6_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			if (_inner_error0_->domain == G_REGEX_ERROR) {
				goto __catch0_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return NULL;
		}
		_tmp8_ = regex;
		_tmp9_ = g_regex_replace_literal (_tmp8_, self, (gssize) -1, 0, replacement, 0, &_inner_error0_);
		_tmp7_ = _tmp9_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_regex_unref0 (regex);
			if (_inner_error0_->domain == G_REGEX_ERROR) {
				goto __catch0_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return NULL;
		}
		_tmp10_ = _tmp7_;
		_tmp7_ = NULL;
		result = _tmp10_;
		_g_free0 (_tmp7_);
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally0;
	__catch0_g_regex_error:
	{
		g_clear_error (&_inner_error0_);
		g_assert_not_reached ();
	}
	__finally0:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
	g_clear_error (&_inner_error0_);
	return NULL;
}

void
komorebi_on_screen_background_window_wallpaperFromUrl (KomorebiOnScreenBackgroundWindow* self,
                                                       gchar* url)
{
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	WebKitWebView* _tmp7_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (url != NULL);
	_tmp0_ = g_strdup_printf ("%i", komorebi_utilities_screenWidth);
	_tmp1_ = _tmp0_;
	_tmp2_ = string_replace (url, "{{screen_width}}", _tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = g_strdup_printf ("%i", komorebi_utilities_screenHeight);
	_tmp5_ = _tmp4_;
	_tmp6_ = string_replace (_tmp3_, "{{screen_height}}", _tmp5_);
	_g_free0 (url);
	url = _tmp6_;
	_g_free0 (_tmp5_);
	_g_free0 (_tmp3_);
	_g_free0 (_tmp1_);
	_tmp7_ = self->priv->webView;
	webkit_web_view_load_uri (_tmp7_, url);
	_g_free0 (url);
}

void
komorebi_on_screen_background_window_fadeIn (KomorebiOnScreenBackgroundWindow* self)
{
	KomorebiOnScreenDateTimeBox* _tmp0_;
	g_return_if_fail (self != NULL);
	gtk_widget_show_all ((GtkWidget*) self);
	_tmp0_ = self->priv->dateTimeBox;
	komorebi_on_screen_date_time_box_setPosition (_tmp0_);
}

gboolean
komorebi_on_screen_background_window_contains_point (KomorebiOnScreenBackgroundWindow* self,
                                                     gint x,
                                                     gint y)
{
	gint wl = 0;
	gint wt = 0;
	gint wr = 0;
	gint wb = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gboolean _tmp4_ = FALSE;
	gboolean _tmp5_ = FALSE;
	gboolean _tmp6_ = FALSE;
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	gtk_window_get_position ((GtkWindow*) self, &_tmp0_, &_tmp1_);
	wl = _tmp0_;
	wt = _tmp1_;
	gtk_window_get_size ((GtkWindow*) self, &_tmp2_, &_tmp3_);
	wr = _tmp2_;
	wb = _tmp3_;
	wr += wl;
	wb += wt;
	if (x >= wl) {
		_tmp6_ = y >= wt;
	} else {
		_tmp6_ = FALSE;
	}
	if (_tmp6_) {
		_tmp5_ = x < wr;
	} else {
		_tmp5_ = FALSE;
	}
	if (_tmp5_) {
		_tmp4_ = y < wb;
	} else {
		_tmp4_ = FALSE;
	}
	result = _tmp4_;
	return result;
}

ClutterActor*
komorebi_on_screen_background_window_get_mainActor (KomorebiOnScreenBackgroundWindow* self)
{
	ClutterActor* result;
	ClutterActor* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_mainActor;
	result = _tmp0_;
	return result;
}

static void
komorebi_on_screen_background_window_set_mainActor (KomorebiOnScreenBackgroundWindow* self,
                                                    ClutterActor* value)
{
	ClutterActor* old_value;
	g_return_if_fail (self != NULL);
	old_value = komorebi_on_screen_background_window_get_mainActor (self);
	if (old_value != value) {
		ClutterActor* _tmp0_;
		_tmp0_ = _g_object_ref0 (value);
		_g_object_unref0 (self->priv->_mainActor);
		self->priv->_mainActor = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, komorebi_on_screen_background_window_properties[KOMOREBI_ON_SCREEN_BACKGROUND_WINDOW_MAIN_ACTOR_PROPERTY]);
	}
}

static void
komorebi_on_screen_background_window_class_init (KomorebiOnScreenBackgroundWindowClass * klass,
                                                 gpointer klass_data)
{
	komorebi_on_screen_background_window_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &KomorebiOnScreenBackgroundWindow_private_offset);
	G_OBJECT_CLASS (klass)->get_property = _vala_komorebi_on_screen_background_window_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_komorebi_on_screen_background_window_set_property;
	G_OBJECT_CLASS (klass)->finalize = komorebi_on_screen_background_window_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), KOMOREBI_ON_SCREEN_BACKGROUND_WINDOW_MAIN_ACTOR_PROPERTY, komorebi_on_screen_background_window_properties[KOMOREBI_ON_SCREEN_BACKGROUND_WINDOW_MAIN_ACTOR_PROPERTY] = g_param_spec_object ("mainActor", "mainActor", "mainActor", clutter_actor_get_type (), G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
}

static void
komorebi_on_screen_background_window_instance_init (KomorebiOnScreenBackgroundWindow * self,
                                                    gpointer klass)
{
	WebKitWebView* _tmp0_;
	ClutterActor* _tmp1_;
	ClutterImage* _tmp2_;
	self->priv = komorebi_on_screen_background_window_get_instance_private (self);
	_tmp0_ = (WebKitWebView*) webkit_web_view_new ();
	g_object_ref_sink (_tmp0_);
	self->priv->webView = _tmp0_;
	_tmp1_ = clutter_actor_new ();
	g_object_ref_sink (_tmp1_);
	self->priv->wallpaperActor = _tmp1_;
	_tmp2_ = (ClutterImage*) clutter_image_new ();
	self->priv->wallpaperImage = _tmp2_;
	self->priv->dateTimeBoxParallax = FALSE;
}

static void
komorebi_on_screen_background_window_finalize (GObject * obj)
{
	KomorebiOnScreenBackgroundWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, KOMOREBI_ON_SCREEN_TYPE_BACKGROUND_WINDOW, KomorebiOnScreenBackgroundWindow);
	_g_object_unref0 (self->priv->webView);
	_g_object_unref0 (self->priv->webViewActor);
	_g_object_unref0 (self->priv->embed);
	_g_object_unref0 (self->priv->_mainActor);
	_g_object_unref0 (self->priv->videoPlayback);
	_g_object_unref0 (self->priv->videoContent);
	_g_object_unref0 (self->priv->wallpaperActor);
	_g_object_unref0 (self->priv->wallpaperPixbuf);
	_g_object_unref0 (self->priv->wallpaperImage);
	_g_object_unref0 (self->priv->dateTimeBox);
	_g_object_unref0 (self->priv->assetActor);
	G_OBJECT_CLASS (komorebi_on_screen_background_window_parent_class)->finalize (obj);
}

static GType
komorebi_on_screen_background_window_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (KomorebiOnScreenBackgroundWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) komorebi_on_screen_background_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (KomorebiOnScreenBackgroundWindow), 0, (GInstanceInitFunc) komorebi_on_screen_background_window_instance_init, NULL };
	GType komorebi_on_screen_background_window_type_id;
	komorebi_on_screen_background_window_type_id = g_type_register_static (gtk_window_get_type (), "KomorebiOnScreenBackgroundWindow", &g_define_type_info, 0);
	KomorebiOnScreenBackgroundWindow_private_offset = g_type_add_instance_private (komorebi_on_screen_background_window_type_id, sizeof (KomorebiOnScreenBackgroundWindowPrivate));
	return komorebi_on_screen_background_window_type_id;
}

GType
komorebi_on_screen_background_window_get_type (void)
{
	static volatile gsize komorebi_on_screen_background_window_type_id__once = 0;
	if (g_once_init_enter (&komorebi_on_screen_background_window_type_id__once)) {
		GType komorebi_on_screen_background_window_type_id;
		komorebi_on_screen_background_window_type_id = komorebi_on_screen_background_window_get_type_once ();
		g_once_init_leave (&komorebi_on_screen_background_window_type_id__once, komorebi_on_screen_background_window_type_id);
	}
	return komorebi_on_screen_background_window_type_id__once;
}

static void
_vala_komorebi_on_screen_background_window_get_property (GObject * object,
                                                         guint property_id,
                                                         GValue * value,
                                                         GParamSpec * pspec)
{
	KomorebiOnScreenBackgroundWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, KOMOREBI_ON_SCREEN_TYPE_BACKGROUND_WINDOW, KomorebiOnScreenBackgroundWindow);
	switch (property_id) {
		case KOMOREBI_ON_SCREEN_BACKGROUND_WINDOW_MAIN_ACTOR_PROPERTY:
		g_value_set_object (value, komorebi_on_screen_background_window_get_mainActor (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_komorebi_on_screen_background_window_set_property (GObject * object,
                                                         guint property_id,
                                                         const GValue * value,
                                                         GParamSpec * pspec)
{
	KomorebiOnScreenBackgroundWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, KOMOREBI_ON_SCREEN_TYPE_BACKGROUND_WINDOW, KomorebiOnScreenBackgroundWindow);
	switch (property_id) {
		case KOMOREBI_ON_SCREEN_BACKGROUND_WINDOW_MAIN_ACTOR_PROPERTY:
		komorebi_on_screen_background_window_set_mainActor (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

