/* DateTimeBox.c generated by valac 0.56.13, the Vala compiler
 * generated from DateTimeBox.vala, do not modify */

#include <clutter/clutter.h>
#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <float.h>
#include <math.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define KOMOREBI_ON_SCREEN_TYPE_DATE_TIME_BOX (komorebi_on_screen_date_time_box_get_type ())
#define KOMOREBI_ON_SCREEN_DATE_TIME_BOX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KOMOREBI_ON_SCREEN_TYPE_DATE_TIME_BOX, KomorebiOnScreenDateTimeBox))
#define KOMOREBI_ON_SCREEN_DATE_TIME_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KOMOREBI_ON_SCREEN_TYPE_DATE_TIME_BOX, KomorebiOnScreenDateTimeBoxClass))
#define KOMOREBI_ON_SCREEN_IS_DATE_TIME_BOX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KOMOREBI_ON_SCREEN_TYPE_DATE_TIME_BOX))
#define KOMOREBI_ON_SCREEN_IS_DATE_TIME_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KOMOREBI_ON_SCREEN_TYPE_DATE_TIME_BOX))
#define KOMOREBI_ON_SCREEN_DATE_TIME_BOX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KOMOREBI_ON_SCREEN_TYPE_DATE_TIME_BOX, KomorebiOnScreenDateTimeBoxClass))

typedef struct _KomorebiOnScreenDateTimeBox KomorebiOnScreenDateTimeBox;
typedef struct _KomorebiOnScreenDateTimeBoxClass KomorebiOnScreenDateTimeBoxClass;
typedef struct _KomorebiOnScreenDateTimeBoxPrivate KomorebiOnScreenDateTimeBoxPrivate;

#define KOMOREBI_ON_SCREEN_TYPE_BACKGROUND_WINDOW (komorebi_on_screen_background_window_get_type ())
#define KOMOREBI_ON_SCREEN_BACKGROUND_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KOMOREBI_ON_SCREEN_TYPE_BACKGROUND_WINDOW, KomorebiOnScreenBackgroundWindow))
#define KOMOREBI_ON_SCREEN_BACKGROUND_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KOMOREBI_ON_SCREEN_TYPE_BACKGROUND_WINDOW, KomorebiOnScreenBackgroundWindowClass))
#define KOMOREBI_ON_SCREEN_IS_BACKGROUND_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KOMOREBI_ON_SCREEN_TYPE_BACKGROUND_WINDOW))
#define KOMOREBI_ON_SCREEN_IS_BACKGROUND_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KOMOREBI_ON_SCREEN_TYPE_BACKGROUND_WINDOW))
#define KOMOREBI_ON_SCREEN_BACKGROUND_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KOMOREBI_ON_SCREEN_TYPE_BACKGROUND_WINDOW, KomorebiOnScreenBackgroundWindowClass))

typedef struct _KomorebiOnScreenBackgroundWindow KomorebiOnScreenBackgroundWindow;
typedef struct _KomorebiOnScreenBackgroundWindowClass KomorebiOnScreenBackgroundWindowClass;
enum  {
	KOMOREBI_ON_SCREEN_DATE_TIME_BOX_0_PROPERTY,
	KOMOREBI_ON_SCREEN_DATE_TIME_BOX_NUM_PROPERTIES
};
static GParamSpec* komorebi_on_screen_date_time_box_properties[KOMOREBI_ON_SCREEN_DATE_TIME_BOX_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))

struct _KomorebiOnScreenDateTimeBox {
	ClutterActor parent_instance;
	KomorebiOnScreenDateTimeBoxPrivate * priv;
	ClutterActor* textContainerActor;
	ClutterText* timeText;
	ClutterText* dateText;
	ClutterActor* shadowContainerActor;
	ClutterText* timeShadowText;
	ClutterText* dateShadowText;
	guint timeout;
};

struct _KomorebiOnScreenDateTimeBoxClass {
	ClutterActorClass parent_class;
};

struct _KomorebiOnScreenDateTimeBoxPrivate {
	ClutterBoxLayout* boxLayout;
	gchar* timeFormat;
	KomorebiOnScreenBackgroundWindow* parent;
};

static gint KomorebiOnScreenDateTimeBox_private_offset;
static gpointer komorebi_on_screen_date_time_box_parent_class = NULL;
VALA_EXTERN gint komorebi_utilities_dateTimeAlpha;
VALA_EXTERN gint komorebi_utilities_dateTimeShadowAlpha;
VALA_EXTERN gchar* komorebi_utilities_dateTimeColor;
VALA_EXTERN gchar* komorebi_utilities_dateTimeTimeFont;
VALA_EXTERN gchar* komorebi_utilities_dateTimeDateFont;
VALA_EXTERN gchar* komorebi_utilities_dateTimeShadowColor;
VALA_EXTERN gchar* komorebi_utilities_dateTimeAlignment;
VALA_EXTERN gdouble komorebi_utilities_dateTimeRotationX;
VALA_EXTERN gdouble komorebi_utilities_dateTimeRotationY;
VALA_EXTERN gdouble komorebi_utilities_dateTimeRotationZ;
VALA_EXTERN gchar* komorebi_utilities_dateTimePosition;
VALA_EXTERN gint komorebi_utilities_dateTimeMarginTop;
VALA_EXTERN gint komorebi_utilities_dateTimeMarginRight;
VALA_EXTERN gint komorebi_utilities_dateTimeMarginLeft;
VALA_EXTERN gint komorebi_utilities_dateTimeMarginBottom;

VALA_EXTERN GType komorebi_on_screen_date_time_box_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KomorebiOnScreenDateTimeBox, g_object_unref)
VALA_EXTERN GType komorebi_on_screen_background_window_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KomorebiOnScreenBackgroundWindow, g_object_unref)
VALA_EXTERN KomorebiOnScreenDateTimeBox* komorebi_on_screen_date_time_box_new (KomorebiOnScreenBackgroundWindow* parent);
VALA_EXTERN KomorebiOnScreenDateTimeBox* komorebi_on_screen_date_time_box_construct (GType object_type,
                                                                         KomorebiOnScreenBackgroundWindow* parent);
VALA_EXTERN void komorebi_on_screen_date_time_box_setDateTime (KomorebiOnScreenDateTimeBox* self);
VALA_EXTERN void komorebi_on_screen_date_time_box_setAlignment (KomorebiOnScreenDateTimeBox* self);
VALA_EXTERN void komorebi_on_screen_date_time_box_setRotation (KomorebiOnScreenDateTimeBox* self);
VALA_EXTERN void komorebi_on_screen_date_time_box_fadeIn (KomorebiOnScreenDateTimeBox* self,
                                              gint custom_duration);
VALA_EXTERN void komorebi_on_screen_date_time_box_setPosition (KomorebiOnScreenDateTimeBox* self);
static void __lambda4_ (KomorebiOnScreenDateTimeBox* self);
VALA_EXTERN void komorebi_on_screen_date_time_box_setMargins (KomorebiOnScreenDateTimeBox* self);
static void ___lambda4__g_object_notify (GObject* _sender,
                                  GParamSpec* pspec,
                                  gpointer self);
static gboolean __lambda5_ (KomorebiOnScreenDateTimeBox* self);
static gboolean ___lambda5__gsource_func (gpointer self);
VALA_EXTERN ClutterActor* komorebi_on_screen_background_window_get_mainActor (KomorebiOnScreenBackgroundWindow* self);
static void komorebi_on_screen_date_time_box_moveTo (KomorebiOnScreenDateTimeBox* self,
                                              gfloat x,
                                              gfloat y);
VALA_EXTERN void komorebi_on_screen_date_time_box_fadeOut (KomorebiOnScreenDateTimeBox* self);
static void komorebi_on_screen_date_time_box_finalize (GObject * obj);
static GType komorebi_on_screen_date_time_box_get_type_once (void);

static inline gpointer
komorebi_on_screen_date_time_box_get_instance_private (KomorebiOnScreenDateTimeBox* self)
{
	return G_STRUCT_MEMBER_P (self, KomorebiOnScreenDateTimeBox_private_offset);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

KomorebiOnScreenDateTimeBox*
komorebi_on_screen_date_time_box_construct (GType object_type,
                                            KomorebiOnScreenBackgroundWindow* parent)
{
	KomorebiOnScreenDateTimeBox * self = NULL;
	KomorebiOnScreenBackgroundWindow* _tmp0_;
	ClutterActor* _tmp1_;
	ClutterBoxLayout* _tmp2_;
	ClutterActor* _tmp3_;
	ClutterBoxLayout* _tmp4_;
	ClutterColor _tmp5_ = {0};
	ClutterActor* _tmp6_;
	ClutterColor _tmp7_ = {0};
	ClutterActor* _tmp8_;
	ClutterColor _tmp9_ = {0};
	ClutterText* _tmp10_;
	ClutterText* _tmp11_;
	ClutterText* _tmp12_;
	ClutterText* _tmp13_;
	ClutterActor* _tmp14_;
	ClutterBlurEffect* _tmp15_;
	ClutterBlurEffect* _tmp16_;
	ClutterActor* _tmp17_;
	ClutterText* _tmp18_;
	ClutterActor* _tmp19_;
	ClutterText* _tmp20_;
	ClutterActor* _tmp21_;
	ClutterText* _tmp22_;
	ClutterActor* _tmp23_;
	ClutterText* _tmp24_;
	ClutterActor* _tmp25_;
	ClutterActor* _tmp26_;
	g_return_val_if_fail (parent != NULL, NULL);
	self = (KomorebiOnScreenDateTimeBox*) g_object_new (object_type, NULL);
	_tmp0_ = _g_object_ref0 (parent);
	_g_object_unref0 (self->priv->parent);
	self->priv->parent = _tmp0_;
	_tmp1_ = self->textContainerActor;
	_tmp2_ = self->priv->boxLayout;
	clutter_actor_set_layout_manager (_tmp1_, (ClutterLayoutManager*) _tmp2_);
	_tmp3_ = self->shadowContainerActor;
	_tmp4_ = self->priv->boxLayout;
	clutter_actor_set_layout_manager (_tmp3_, (ClutterLayoutManager*) _tmp4_);
	_tmp5_.red = (guint8) 0;
	_tmp5_.green = (guint8) 0;
	_tmp5_.blue = (guint8) 0;
	_tmp5_.alpha = (guint8) 0;
	clutter_actor_set_background_color ((ClutterActor*) self, &_tmp5_);
	clutter_actor_set_opacity ((ClutterActor*) self, (guint) 0);
	clutter_actor_set_reactive ((ClutterActor*) self, TRUE);
	_tmp6_ = self->textContainerActor;
	_tmp7_.red = (guint8) 0;
	_tmp7_.green = (guint8) 0;
	_tmp7_.blue = (guint8) 0;
	_tmp7_.alpha = (guint8) 0;
	clutter_actor_set_background_color (_tmp6_, &_tmp7_);
	_tmp8_ = self->shadowContainerActor;
	_tmp9_.red = (guint8) 0;
	_tmp9_.green = (guint8) 0;
	_tmp9_.blue = (guint8) 0;
	_tmp9_.alpha = (guint8) 0;
	clutter_actor_set_background_color (_tmp8_, &_tmp9_);
	_tmp10_ = self->timeText;
	clutter_actor_set_x_expand ((ClutterActor*) _tmp10_, TRUE);
	_tmp11_ = self->timeText;
	clutter_actor_set_y_expand ((ClutterActor*) _tmp11_, TRUE);
	_tmp12_ = self->timeShadowText;
	clutter_actor_set_x_expand ((ClutterActor*) _tmp12_, TRUE);
	_tmp13_ = self->timeShadowText;
	clutter_actor_set_y_expand ((ClutterActor*) _tmp13_, TRUE);
	_tmp14_ = self->shadowContainerActor;
	_tmp15_ = (ClutterBlurEffect*) clutter_blur_effect_new ();
	g_object_ref_sink (_tmp15_);
	_tmp16_ = _tmp15_;
	clutter_actor_add_effect (_tmp14_, (ClutterEffect*) _tmp16_);
	_g_object_unref0 (_tmp16_);
	_tmp17_ = self->textContainerActor;
	_tmp18_ = self->timeText;
	clutter_actor_add_child (_tmp17_, (ClutterActor*) _tmp18_);
	_tmp19_ = self->textContainerActor;
	_tmp20_ = self->dateText;
	clutter_actor_add_child (_tmp19_, (ClutterActor*) _tmp20_);
	_tmp21_ = self->shadowContainerActor;
	_tmp22_ = self->timeShadowText;
	clutter_actor_add_child (_tmp21_, (ClutterActor*) _tmp22_);
	_tmp23_ = self->shadowContainerActor;
	_tmp24_ = self->dateShadowText;
	clutter_actor_add_child (_tmp23_, (ClutterActor*) _tmp24_);
	_tmp25_ = self->shadowContainerActor;
	clutter_actor_add_child ((ClutterActor*) self, _tmp25_);
	_tmp26_ = self->textContainerActor;
	clutter_actor_add_child ((ClutterActor*) self, _tmp26_);
	return self;
}

KomorebiOnScreenDateTimeBox*
komorebi_on_screen_date_time_box_new (KomorebiOnScreenBackgroundWindow* parent)
{
	return komorebi_on_screen_date_time_box_construct (KOMOREBI_ON_SCREEN_TYPE_DATE_TIME_BOX, parent);
}

static void
__lambda4_ (KomorebiOnScreenDateTimeBox* self)
{
	komorebi_on_screen_date_time_box_setPosition (self);
	komorebi_on_screen_date_time_box_setMargins (self);
}

static void
___lambda4__g_object_notify (GObject* _sender,
                             GParamSpec* pspec,
                             gpointer self)
{
	__lambda4_ ((KomorebiOnScreenDateTimeBox*) self);
}

static const gchar*
string_to_string (const gchar* self)
{
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}

static gboolean
__lambda5_ (KomorebiOnScreenDateTimeBox* self)
{
	gchar* glibTime = NULL;
	GDateTime* _tmp0_;
	GDateTime* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* glibDate = NULL;
	GDateTime* _tmp4_;
	GDateTime* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	ClutterText* _tmp8_;
	const gchar* _tmp9_;
	const gchar* _tmp10_;
	const gchar* _tmp11_;
	const gchar* _tmp12_;
	const gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	ClutterText* _tmp16_;
	const gchar* _tmp17_;
	const gchar* _tmp18_;
	const gchar* _tmp19_;
	const gchar* _tmp20_;
	const gchar* _tmp21_;
	gchar* _tmp22_;
	gchar* _tmp23_;
	ClutterText* _tmp24_;
	const gchar* _tmp25_;
	const gchar* _tmp26_;
	const gchar* _tmp27_;
	const gchar* _tmp28_;
	const gchar* _tmp29_;
	gchar* _tmp30_;
	gchar* _tmp31_;
	ClutterText* _tmp32_;
	const gchar* _tmp33_;
	const gchar* _tmp34_;
	const gchar* _tmp35_;
	const gchar* _tmp36_;
	const gchar* _tmp37_;
	gchar* _tmp38_;
	gchar* _tmp39_;
	gboolean result;
	_tmp0_ = g_date_time_new_now_local ();
	_tmp1_ = _tmp0_;
	_tmp2_ = g_date_time_format (_tmp1_, "%H:%M");
	_tmp3_ = _tmp2_;
	_g_date_time_unref0 (_tmp1_);
	glibTime = _tmp3_;
	_tmp4_ = g_date_time_new_now_local ();
	_tmp5_ = _tmp4_;
	_tmp6_ = g_date_time_format (_tmp5_, "%A, %B %e");
	_tmp7_ = _tmp6_;
	_g_date_time_unref0 (_tmp5_);
	glibDate = _tmp7_;
	_tmp8_ = self->timeText;
	_tmp9_ = komorebi_utilities_dateTimeColor;
	_tmp10_ = string_to_string (_tmp9_);
	_tmp11_ = komorebi_utilities_dateTimeTimeFont;
	_tmp12_ = string_to_string (_tmp11_);
	_tmp13_ = string_to_string (glibTime);
	_tmp14_ = g_strconcat ("<span color='", _tmp10_, "' font='", _tmp12_, "'>", _tmp13_, "</span>", NULL);
	_tmp15_ = _tmp14_;
	clutter_text_set_markup (_tmp8_, _tmp15_);
	_g_free0 (_tmp15_);
	_tmp16_ = self->dateText;
	_tmp17_ = komorebi_utilities_dateTimeColor;
	_tmp18_ = string_to_string (_tmp17_);
	_tmp19_ = komorebi_utilities_dateTimeDateFont;
	_tmp20_ = string_to_string (_tmp19_);
	_tmp21_ = string_to_string (glibDate);
	_tmp22_ = g_strconcat ("<span color='", _tmp18_, "' font='", _tmp20_, "'>", _tmp21_, "</span>", NULL);
	_tmp23_ = _tmp22_;
	clutter_text_set_markup (_tmp16_, _tmp23_);
	_g_free0 (_tmp23_);
	_tmp24_ = self->timeShadowText;
	_tmp25_ = komorebi_utilities_dateTimeShadowColor;
	_tmp26_ = string_to_string (_tmp25_);
	_tmp27_ = komorebi_utilities_dateTimeTimeFont;
	_tmp28_ = string_to_string (_tmp27_);
	_tmp29_ = string_to_string (glibTime);
	_tmp30_ = g_strconcat ("<span color='", _tmp26_, "' font='", _tmp28_, "'>", _tmp29_, "</span>", NULL);
	_tmp31_ = _tmp30_;
	clutter_text_set_markup (_tmp24_, _tmp31_);
	_g_free0 (_tmp31_);
	_tmp32_ = self->dateShadowText;
	_tmp33_ = komorebi_utilities_dateTimeShadowColor;
	_tmp34_ = string_to_string (_tmp33_);
	_tmp35_ = komorebi_utilities_dateTimeDateFont;
	_tmp36_ = string_to_string (_tmp35_);
	_tmp37_ = string_to_string (glibDate);
	_tmp38_ = g_strconcat ("<span color='", _tmp34_, "' font='", _tmp36_, "'>", _tmp37_, "</span>", NULL);
	_tmp39_ = _tmp38_;
	clutter_text_set_markup (_tmp32_, _tmp39_);
	_g_free0 (_tmp39_);
	result = TRUE;
	_g_free0 (glibDate);
	_g_free0 (glibTime);
	return result;
}

static gboolean
___lambda5__gsource_func (gpointer self)
{
	gboolean result;
	result = __lambda5_ ((KomorebiOnScreenDateTimeBox*) self);
	return result;
}

void
komorebi_on_screen_date_time_box_setDateTime (KomorebiOnScreenDateTimeBox* self)
{
	guint _tmp0_;
	guint _tmp1_;
	ClutterActor* _tmp2_;
	ClutterText* _tmp3_;
	g_return_if_fail (self != NULL);
	komorebi_on_screen_date_time_box_setAlignment (self);
	komorebi_on_screen_date_time_box_setRotation (self);
	_tmp0_ = clutter_actor_get_opacity ((ClutterActor*) self);
	_tmp1_ = _tmp0_;
	if (_tmp1_ < ((guint) 1)) {
		komorebi_on_screen_date_time_box_fadeIn (self, 90);
	}
	clutter_actor_set_opacity ((ClutterActor*) self, (guint) komorebi_utilities_dateTimeAlpha);
	_tmp2_ = self->shadowContainerActor;
	clutter_actor_set_opacity (_tmp2_, (guint) komorebi_utilities_dateTimeShadowAlpha);
	komorebi_on_screen_date_time_box_setPosition (self);
	_tmp3_ = self->timeText;
	g_signal_connect_object ((GObject*) _tmp3_, "notify::width", (GCallback) ___lambda4__g_object_notify, self, 0);
	if (self->timeout > ((guint) 0)) {
		return;
	}
	self->timeout = g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) 200, ___lambda5__gsource_func, g_object_ref (self), g_object_unref);
}

void
komorebi_on_screen_date_time_box_setAlignment (KomorebiOnScreenDateTimeBox* self)
{
	const gchar* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = komorebi_utilities_dateTimeAlignment;
	if (g_strcmp0 (_tmp0_, "start") == 0) {
		ClutterText* _tmp1_;
		ClutterText* _tmp2_;
		_tmp1_ = self->timeText;
		clutter_actor_set_x_align ((ClutterActor*) _tmp1_, CLUTTER_ACTOR_ALIGN_START);
		_tmp2_ = self->timeShadowText;
		clutter_actor_set_x_align ((ClutterActor*) _tmp2_, CLUTTER_ACTOR_ALIGN_START);
	} else {
		const gchar* _tmp3_;
		_tmp3_ = komorebi_utilities_dateTimeAlignment;
		if (g_strcmp0 (_tmp3_, "center") == 0) {
			ClutterText* _tmp4_;
			ClutterText* _tmp5_;
			_tmp4_ = self->timeText;
			clutter_actor_set_x_align ((ClutterActor*) _tmp4_, CLUTTER_ACTOR_ALIGN_CENTER);
			_tmp5_ = self->timeShadowText;
			clutter_actor_set_x_align ((ClutterActor*) _tmp5_, CLUTTER_ACTOR_ALIGN_CENTER);
		} else {
			ClutterText* _tmp6_;
			ClutterText* _tmp7_;
			_tmp6_ = self->timeText;
			clutter_actor_set_x_align ((ClutterActor*) _tmp6_, CLUTTER_ACTOR_ALIGN_END);
			_tmp7_ = self->timeShadowText;
			clutter_actor_set_x_align ((ClutterActor*) _tmp7_, CLUTTER_ACTOR_ALIGN_END);
		}
	}
}

void
komorebi_on_screen_date_time_box_setRotation (KomorebiOnScreenDateTimeBox* self)
{
	g_return_if_fail (self != NULL);
	g_object_set ((ClutterActor*) self, "rotation-angle-x", komorebi_utilities_dateTimeRotationX, NULL);
	g_object_set ((ClutterActor*) self, "rotation-angle-y", komorebi_utilities_dateTimeRotationY, NULL);
	g_object_set ((ClutterActor*) self, "rotation-angle-z", komorebi_utilities_dateTimeRotationZ, NULL);
}

void
komorebi_on_screen_date_time_box_setPosition (KomorebiOnScreenDateTimeBox* self)
{
	ClutterActor* mainActor = NULL;
	KomorebiOnScreenBackgroundWindow* _tmp0_;
	ClutterActor* _tmp1_;
	ClutterActor* _tmp2_;
	ClutterActor* _tmp3_;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
	GQuark _tmp7_ = 0U;
	static GQuark _tmp6_label0 = 0;
	static GQuark _tmp6_label1 = 0;
	static GQuark _tmp6_label2 = 0;
	static GQuark _tmp6_label3 = 0;
	static GQuark _tmp6_label4 = 0;
	static GQuark _tmp6_label5 = 0;
	static GQuark _tmp6_label6 = 0;
	static GQuark _tmp6_label7 = 0;
	static GQuark _tmp6_label8 = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->parent;
	_tmp1_ = komorebi_on_screen_background_window_get_mainActor (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	mainActor = _tmp3_;
	_tmp4_ = komorebi_utilities_dateTimePosition;
	_tmp5_ = _tmp4_;
	_tmp7_ = (NULL == _tmp5_) ? 0 : g_quark_from_string (_tmp5_);
	if (_tmp7_ == ((0 != _tmp6_label0) ? _tmp6_label0 : (_tmp6_label0 = g_quark_from_static_string ("top_right")))) {
		switch (0) {
			default:
			{
				ClutterActor* _tmp8_;
				gfloat _tmp9_;
				gfloat _tmp10_;
				gfloat _tmp11_;
				gfloat _tmp12_;
				_tmp8_ = mainActor;
				_tmp9_ = clutter_actor_get_width (_tmp8_);
				_tmp10_ = _tmp9_;
				_tmp11_ = clutter_actor_get_width ((ClutterActor*) self);
				_tmp12_ = _tmp11_;
				clutter_actor_set_x ((ClutterActor*) self, _tmp10_ - _tmp12_);
				clutter_actor_set_y ((ClutterActor*) self, (gfloat) 0);
				break;
			}
		}
	} else if (_tmp7_ == ((0 != _tmp6_label1) ? _tmp6_label1 : (_tmp6_label1 = g_quark_from_static_string ("top_center")))) {
		switch (0) {
			default:
			{
				ClutterActor* _tmp13_;
				gfloat _tmp14_;
				gfloat _tmp15_;
				gfloat _tmp16_;
				gfloat _tmp17_;
				_tmp13_ = mainActor;
				_tmp14_ = clutter_actor_get_width (_tmp13_);
				_tmp15_ = _tmp14_;
				_tmp16_ = clutter_actor_get_width ((ClutterActor*) self);
				_tmp17_ = _tmp16_;
				clutter_actor_set_x ((ClutterActor*) self, (_tmp15_ / 2) - (_tmp17_ / 2));
				clutter_actor_set_y ((ClutterActor*) self, (gfloat) 0);
				break;
			}
		}
	} else if (_tmp7_ == ((0 != _tmp6_label2) ? _tmp6_label2 : (_tmp6_label2 = g_quark_from_static_string ("top_left")))) {
		switch (0) {
			default:
			{
				clutter_actor_set_x ((ClutterActor*) self, (gfloat) 0);
				clutter_actor_set_y ((ClutterActor*) self, (gfloat) 0);
				break;
			}
		}
	} else if (_tmp7_ == ((0 != _tmp6_label3) ? _tmp6_label3 : (_tmp6_label3 = g_quark_from_static_string ("center_right")))) {
		switch (0) {
			default:
			{
				ClutterActor* _tmp18_;
				gfloat _tmp19_;
				gfloat _tmp20_;
				gfloat _tmp21_;
				gfloat _tmp22_;
				ClutterActor* _tmp23_;
				gfloat _tmp24_;
				gfloat _tmp25_;
				gfloat _tmp26_;
				gfloat _tmp27_;
				_tmp18_ = mainActor;
				_tmp19_ = clutter_actor_get_width (_tmp18_);
				_tmp20_ = _tmp19_;
				_tmp21_ = clutter_actor_get_width ((ClutterActor*) self);
				_tmp22_ = _tmp21_;
				clutter_actor_set_x ((ClutterActor*) self, _tmp20_ - _tmp22_);
				_tmp23_ = mainActor;
				_tmp24_ = clutter_actor_get_height (_tmp23_);
				_tmp25_ = _tmp24_;
				_tmp26_ = clutter_actor_get_height ((ClutterActor*) self);
				_tmp27_ = _tmp26_;
				clutter_actor_set_y ((ClutterActor*) self, (_tmp25_ / 2) - (_tmp27_ / 2));
				break;
			}
		}
	} else if (_tmp7_ == ((0 != _tmp6_label4) ? _tmp6_label4 : (_tmp6_label4 = g_quark_from_static_string ("center")))) {
		switch (0) {
			default:
			{
				ClutterActor* _tmp28_;
				gfloat _tmp29_;
				gfloat _tmp30_;
				gfloat _tmp31_;
				gfloat _tmp32_;
				ClutterActor* _tmp33_;
				gfloat _tmp34_;
				gfloat _tmp35_;
				gfloat _tmp36_;
				gfloat _tmp37_;
				_tmp28_ = mainActor;
				_tmp29_ = clutter_actor_get_width (_tmp28_);
				_tmp30_ = _tmp29_;
				_tmp31_ = clutter_actor_get_width ((ClutterActor*) self);
				_tmp32_ = _tmp31_;
				clutter_actor_set_x ((ClutterActor*) self, (_tmp30_ / 2) - (_tmp32_ / 2));
				_tmp33_ = mainActor;
				_tmp34_ = clutter_actor_get_height (_tmp33_);
				_tmp35_ = _tmp34_;
				_tmp36_ = clutter_actor_get_height ((ClutterActor*) self);
				_tmp37_ = _tmp36_;
				clutter_actor_set_y ((ClutterActor*) self, (_tmp35_ / 2) - (_tmp37_ / 2));
				break;
			}
		}
	} else if (_tmp7_ == ((0 != _tmp6_label5) ? _tmp6_label5 : (_tmp6_label5 = g_quark_from_static_string ("center_left")))) {
		switch (0) {
			default:
			{
				ClutterActor* _tmp38_;
				gfloat _tmp39_;
				gfloat _tmp40_;
				gfloat _tmp41_;
				gfloat _tmp42_;
				clutter_actor_set_x ((ClutterActor*) self, (gfloat) 0);
				_tmp38_ = mainActor;
				_tmp39_ = clutter_actor_get_height (_tmp38_);
				_tmp40_ = _tmp39_;
				_tmp41_ = clutter_actor_get_height ((ClutterActor*) self);
				_tmp42_ = _tmp41_;
				clutter_actor_set_y ((ClutterActor*) self, (_tmp40_ / 2) - (_tmp42_ / 2));
				break;
			}
		}
	} else if (_tmp7_ == ((0 != _tmp6_label6) ? _tmp6_label6 : (_tmp6_label6 = g_quark_from_static_string ("bottom_right")))) {
		switch (0) {
			default:
			{
				ClutterActor* _tmp43_;
				gfloat _tmp44_;
				gfloat _tmp45_;
				gfloat _tmp46_;
				gfloat _tmp47_;
				ClutterActor* _tmp48_;
				gfloat _tmp49_;
				gfloat _tmp50_;
				gfloat _tmp51_;
				gfloat _tmp52_;
				_tmp43_ = mainActor;
				_tmp44_ = clutter_actor_get_width (_tmp43_);
				_tmp45_ = _tmp44_;
				_tmp46_ = clutter_actor_get_width ((ClutterActor*) self);
				_tmp47_ = _tmp46_;
				clutter_actor_set_x ((ClutterActor*) self, _tmp45_ - _tmp47_);
				_tmp48_ = mainActor;
				_tmp49_ = clutter_actor_get_height (_tmp48_);
				_tmp50_ = _tmp49_;
				_tmp51_ = clutter_actor_get_height ((ClutterActor*) self);
				_tmp52_ = _tmp51_;
				clutter_actor_set_y ((ClutterActor*) self, _tmp50_ - _tmp52_);
				break;
			}
		}
	} else if (_tmp7_ == ((0 != _tmp6_label7) ? _tmp6_label7 : (_tmp6_label7 = g_quark_from_static_string ("bottom_center")))) {
		switch (0) {
			default:
			{
				ClutterActor* _tmp53_;
				gfloat _tmp54_;
				gfloat _tmp55_;
				gfloat _tmp56_;
				gfloat _tmp57_;
				ClutterActor* _tmp58_;
				gfloat _tmp59_;
				gfloat _tmp60_;
				gfloat _tmp61_;
				gfloat _tmp62_;
				_tmp53_ = mainActor;
				_tmp54_ = clutter_actor_get_width (_tmp53_);
				_tmp55_ = _tmp54_;
				_tmp56_ = clutter_actor_get_width ((ClutterActor*) self);
				_tmp57_ = _tmp56_;
				clutter_actor_set_x ((ClutterActor*) self, (_tmp55_ / 2) - (_tmp57_ / 2));
				_tmp58_ = mainActor;
				_tmp59_ = clutter_actor_get_height (_tmp58_);
				_tmp60_ = _tmp59_;
				_tmp61_ = clutter_actor_get_height ((ClutterActor*) self);
				_tmp62_ = _tmp61_;
				clutter_actor_set_y ((ClutterActor*) self, _tmp60_ - _tmp62_);
				break;
			}
		}
	} else if (_tmp7_ == ((0 != _tmp6_label8) ? _tmp6_label8 : (_tmp6_label8 = g_quark_from_static_string ("bottom_left")))) {
		switch (0) {
			default:
			{
				ClutterActor* _tmp63_;
				gfloat _tmp64_;
				gfloat _tmp65_;
				gfloat _tmp66_;
				gfloat _tmp67_;
				clutter_actor_set_x ((ClutterActor*) self, (gfloat) 0);
				_tmp63_ = mainActor;
				_tmp64_ = clutter_actor_get_height (_tmp63_);
				_tmp65_ = _tmp64_;
				_tmp66_ = clutter_actor_get_height ((ClutterActor*) self);
				_tmp67_ = _tmp66_;
				clutter_actor_set_y ((ClutterActor*) self, _tmp65_ - _tmp67_);
				break;
			}
		}
	} else {
		switch (0) {
			default:
			{
				break;
			}
		}
	}
	_g_object_unref0 (mainActor);
}

void
komorebi_on_screen_date_time_box_setMargins (KomorebiOnScreenDateTimeBox* self)
{
	gfloat _tmp0_;
	gfloat _tmp1_;
	gfloat _tmp2_;
	gfloat _tmp3_;
	gfloat _tmp4_;
	gfloat _tmp5_;
	gfloat _tmp6_;
	gfloat _tmp7_;
	g_return_if_fail (self != NULL);
	g_object_set ((ClutterActor*) self, "translation-y", (gfloat) 0, NULL);
	g_object_set ((ClutterActor*) self, "translation-x", (gfloat) 0, NULL);
	g_object_get ((ClutterActor*) self, "translation-y", &_tmp0_, NULL);
	_tmp1_ = _tmp0_;
	g_object_set ((ClutterActor*) self, "translation-y", _tmp1_ + komorebi_utilities_dateTimeMarginTop, NULL);
	g_object_get ((ClutterActor*) self, "translation-x", &_tmp2_, NULL);
	_tmp3_ = _tmp2_;
	g_object_set ((ClutterActor*) self, "translation-x", _tmp3_ - komorebi_utilities_dateTimeMarginRight, NULL);
	g_object_get ((ClutterActor*) self, "translation-x", &_tmp4_, NULL);
	_tmp5_ = _tmp4_;
	g_object_set ((ClutterActor*) self, "translation-x", _tmp5_ + komorebi_utilities_dateTimeMarginLeft, NULL);
	g_object_get ((ClutterActor*) self, "translation-y", &_tmp6_, NULL);
	_tmp7_ = _tmp6_;
	g_object_set ((ClutterActor*) self, "translation-y", _tmp7_ - komorebi_utilities_dateTimeMarginBottom, NULL);
}

static void
komorebi_on_screen_date_time_box_moveTo (KomorebiOnScreenDateTimeBox* self,
                                         gfloat x,
                                         gfloat y)
{
	g_return_if_fail (self != NULL);
	clutter_actor_save_easing_state ((ClutterActor*) self);
	clutter_actor_set_easing_duration ((ClutterActor*) self, (guint) 90);
	if (x != ((gfloat) -1)) {
		clutter_actor_set_x ((ClutterActor*) self, x);
	}
	if (y != ((gfloat) -1)) {
		clutter_actor_set_y ((ClutterActor*) self, y);
	}
	clutter_actor_set_easing_mode ((ClutterActor*) self, CLUTTER_EASE_IN_SINE);
	clutter_actor_restore_easing_state ((ClutterActor*) self);
}

void
komorebi_on_screen_date_time_box_fadeIn (KomorebiOnScreenDateTimeBox* self,
                                         gint custom_duration)
{
	g_return_if_fail (self != NULL);
	clutter_actor_save_easing_state ((ClutterActor*) self);
	clutter_actor_set_easing_duration ((ClutterActor*) self, (guint) 90);
	clutter_actor_set_opacity ((ClutterActor*) self, (guint) komorebi_utilities_dateTimeAlpha);
	clutter_actor_set_easing_mode ((ClutterActor*) self, CLUTTER_EASE_IN_SINE);
	clutter_actor_restore_easing_state ((ClutterActor*) self);
	clutter_actor_set_reactive ((ClutterActor*) self, TRUE);
}

void
komorebi_on_screen_date_time_box_fadeOut (KomorebiOnScreenDateTimeBox* self)
{
	g_return_if_fail (self != NULL);
	clutter_actor_save_easing_state ((ClutterActor*) self);
	clutter_actor_set_easing_duration ((ClutterActor*) self, (guint) 90);
	clutter_actor_set_opacity ((ClutterActor*) self, (guint) 0);
	clutter_actor_set_easing_mode ((ClutterActor*) self, CLUTTER_EASE_IN_SINE);
	clutter_actor_restore_easing_state ((ClutterActor*) self);
	clutter_actor_set_reactive ((ClutterActor*) self, FALSE);
}

static void
komorebi_on_screen_date_time_box_class_init (KomorebiOnScreenDateTimeBoxClass * klass,
                                             gpointer klass_data)
{
	komorebi_on_screen_date_time_box_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &KomorebiOnScreenDateTimeBox_private_offset);
	G_OBJECT_CLASS (klass)->finalize = komorebi_on_screen_date_time_box_finalize;
}

static void
komorebi_on_screen_date_time_box_instance_init (KomorebiOnScreenDateTimeBox * self,
                                                gpointer klass)
{
	ClutterActor* _tmp0_;
	ClutterText* _tmp1_;
	ClutterText* _tmp2_;
	ClutterActor* _tmp3_;
	ClutterText* _tmp4_;
	ClutterText* _tmp5_;
	ClutterBoxLayout* _tmp6_ = NULL;
	gchar* _tmp7_;
	self->priv = komorebi_on_screen_date_time_box_get_instance_private (self);
	_tmp0_ = clutter_actor_new ();
	g_object_ref_sink (_tmp0_);
	self->textContainerActor = _tmp0_;
	_tmp1_ = (ClutterText*) clutter_text_new ();
	g_object_ref_sink (_tmp1_);
	self->timeText = _tmp1_;
	_tmp2_ = (ClutterText*) clutter_text_new ();
	g_object_ref_sink (_tmp2_);
	self->dateText = _tmp2_;
	_tmp3_ = clutter_actor_new ();
	g_object_ref_sink (_tmp3_);
	self->shadowContainerActor = _tmp3_;
	_tmp4_ = (ClutterText*) clutter_text_new ();
	g_object_ref_sink (_tmp4_);
	self->timeShadowText = _tmp4_;
	_tmp5_ = (ClutterText*) clutter_text_new ();
	g_object_ref_sink (_tmp5_);
	self->dateShadowText = _tmp5_;
	_tmp6_ = (ClutterBoxLayout*) clutter_box_layout_new ();
	clutter_box_layout_set_orientation (_tmp6_, CLUTTER_ORIENTATION_VERTICAL);
	g_object_ref_sink (_tmp6_);
	self->priv->boxLayout = _tmp6_;
	_tmp7_ = g_strdup ("%l:%M %p");
	self->priv->timeFormat = _tmp7_;
}

static void
komorebi_on_screen_date_time_box_finalize (GObject * obj)
{
	KomorebiOnScreenDateTimeBox * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, KOMOREBI_ON_SCREEN_TYPE_DATE_TIME_BOX, KomorebiOnScreenDateTimeBox);
	_g_object_unref0 (self->textContainerActor);
	_g_object_unref0 (self->timeText);
	_g_object_unref0 (self->dateText);
	_g_object_unref0 (self->shadowContainerActor);
	_g_object_unref0 (self->timeShadowText);
	_g_object_unref0 (self->dateShadowText);
	_g_object_unref0 (self->priv->boxLayout);
	_g_free0 (self->priv->timeFormat);
	_g_object_unref0 (self->priv->parent);
	G_OBJECT_CLASS (komorebi_on_screen_date_time_box_parent_class)->finalize (obj);
}

static GType
komorebi_on_screen_date_time_box_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (KomorebiOnScreenDateTimeBoxClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) komorebi_on_screen_date_time_box_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (KomorebiOnScreenDateTimeBox), 0, (GInstanceInitFunc) komorebi_on_screen_date_time_box_instance_init, NULL };
	GType komorebi_on_screen_date_time_box_type_id;
	komorebi_on_screen_date_time_box_type_id = g_type_register_static (clutter_actor_get_type (), "KomorebiOnScreenDateTimeBox", &g_define_type_info, 0);
	KomorebiOnScreenDateTimeBox_private_offset = g_type_add_instance_private (komorebi_on_screen_date_time_box_type_id, sizeof (KomorebiOnScreenDateTimeBoxPrivate));
	return komorebi_on_screen_date_time_box_type_id;
}

GType
komorebi_on_screen_date_time_box_get_type (void)
{
	static volatile gsize komorebi_on_screen_date_time_box_type_id__once = 0;
	if (g_once_init_enter (&komorebi_on_screen_date_time_box_type_id__once)) {
		GType komorebi_on_screen_date_time_box_type_id;
		komorebi_on_screen_date_time_box_type_id = komorebi_on_screen_date_time_box_get_type_once ();
		g_once_init_leave (&komorebi_on_screen_date_time_box_type_id__once, komorebi_on_screen_date_time_box_type_id);
	}
	return komorebi_on_screen_date_time_box_type_id__once;
}

