/* Utilities.c generated by valac 0.56.13, the Vala compiler
 * generated from Utilities.vala, do not modify */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gio/gio.h>
#include <float.h>
#include <math.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_key_file_unref0(var) ((var == NULL) ? NULL : (var = (g_key_file_unref (var), NULL)))
#define _g_settings_schema_unref0(var) ((var == NULL) ? NULL : (var = (g_settings_schema_unref (var), NULL)))
#define _g_settings_schema_source_unref0(var) ((var == NULL) ? NULL : (var = (g_settings_schema_source_unref (var), NULL)))

VALA_EXTERN gchar* komorebi_utilities_desktopPath;
gchar* komorebi_utilities_desktopPath = NULL;
VALA_EXTERN gchar* komorebi_utilities_configFilePath;
gchar* komorebi_utilities_configFilePath = NULL;
VALA_EXTERN GFile* komorebi_utilities_configFile;
GFile* komorebi_utilities_configFile = NULL;
VALA_EXTERN GKeyFile* komorebi_utilities_configKeyFile;
GKeyFile* komorebi_utilities_configKeyFile = NULL;
VALA_EXTERN gint komorebi_utilities_screenHeight;
gint komorebi_utilities_screenHeight = 0;
VALA_EXTERN gint komorebi_utilities_screenWidth;
gint komorebi_utilities_screenWidth = 0;
VALA_EXTERN gboolean komorebi_utilities_dateTimeParallax;
gboolean komorebi_utilities_dateTimeParallax = FALSE;
VALA_EXTERN gboolean komorebi_utilities_dateTimeVisible;
gboolean komorebi_utilities_dateTimeVisible = FALSE;
VALA_EXTERN gint komorebi_utilities_dateTimeMarginTop;
gint komorebi_utilities_dateTimeMarginTop = 0;
VALA_EXTERN gint komorebi_utilities_dateTimeMarginRight;
gint komorebi_utilities_dateTimeMarginRight = 0;
VALA_EXTERN gint komorebi_utilities_dateTimeMarginLeft;
gint komorebi_utilities_dateTimeMarginLeft = 0;
VALA_EXTERN gint komorebi_utilities_dateTimeMarginBottom;
gint komorebi_utilities_dateTimeMarginBottom = 0;
VALA_EXTERN gdouble komorebi_utilities_dateTimeRotationX;
gdouble komorebi_utilities_dateTimeRotationX = 0.0;
VALA_EXTERN gdouble komorebi_utilities_dateTimeRotationY;
gdouble komorebi_utilities_dateTimeRotationY = 0.0;
VALA_EXTERN gdouble komorebi_utilities_dateTimeRotationZ;
gdouble komorebi_utilities_dateTimeRotationZ = 0.0;
VALA_EXTERN gchar* komorebi_utilities_dateTimePosition;
gchar* komorebi_utilities_dateTimePosition = NULL;
VALA_EXTERN gchar* komorebi_utilities_dateTimeAlignment;
gchar* komorebi_utilities_dateTimeAlignment = NULL;
VALA_EXTERN gboolean komorebi_utilities_dateTimeAlwaysOnTop;
gboolean komorebi_utilities_dateTimeAlwaysOnTop = FALSE;
VALA_EXTERN gchar* komorebi_utilities_dateTimeColor;
gchar* komorebi_utilities_dateTimeColor = NULL;
VALA_EXTERN gint komorebi_utilities_dateTimeAlpha;
gint komorebi_utilities_dateTimeAlpha = 0;
VALA_EXTERN gchar* komorebi_utilities_dateTimeShadowColor;
gchar* komorebi_utilities_dateTimeShadowColor = NULL;
VALA_EXTERN gint komorebi_utilities_dateTimeShadowAlpha;
gint komorebi_utilities_dateTimeShadowAlpha = 0;
VALA_EXTERN gchar* komorebi_utilities_dateTimeTimeFont;
gchar* komorebi_utilities_dateTimeTimeFont = NULL;
VALA_EXTERN gchar* komorebi_utilities_dateTimeDateFont;
gchar* komorebi_utilities_dateTimeDateFont = NULL;
VALA_EXTERN GKeyFile* komorebi_utilities_wallpaperKeyFile;
GKeyFile* komorebi_utilities_wallpaperKeyFile = NULL;
VALA_EXTERN gchar* komorebi_utilities_wallpaperType;
gchar* komorebi_utilities_wallpaperType = NULL;
VALA_EXTERN gchar* komorebi_utilities_videoFileName;
gchar* komorebi_utilities_videoFileName = NULL;
VALA_EXTERN gchar* komorebi_utilities_webPageUrl;
gchar* komorebi_utilities_webPageUrl = NULL;
VALA_EXTERN gboolean komorebi_utilities_wallpaperParallax;
gboolean komorebi_utilities_wallpaperParallax = FALSE;
VALA_EXTERN gboolean komorebi_utilities_assetVisible;
gboolean komorebi_utilities_assetVisible = FALSE;
VALA_EXTERN gint komorebi_utilities_assetWidth;
gint komorebi_utilities_assetWidth = 0;
VALA_EXTERN gint komorebi_utilities_assetHeight;
gint komorebi_utilities_assetHeight = 0;
VALA_EXTERN gchar* komorebi_utilities_assetAnimationMode;
gchar* komorebi_utilities_assetAnimationMode = NULL;
VALA_EXTERN gint komorebi_utilities_assetAnimationSpeed;
gint komorebi_utilities_assetAnimationSpeed = 0;
VALA_EXTERN gchar* komorebi_utilities_assetPosition;
gchar* komorebi_utilities_assetPosition = NULL;
VALA_EXTERN gint komorebi_utilities_assetMarginTop;
gint komorebi_utilities_assetMarginTop = 0;
VALA_EXTERN gint komorebi_utilities_assetMarginRight;
gint komorebi_utilities_assetMarginRight = 0;
VALA_EXTERN gint komorebi_utilities_assetMarginLeft;
gint komorebi_utilities_assetMarginLeft = 0;
VALA_EXTERN gint komorebi_utilities_assetMarginBottom;
gint komorebi_utilities_assetMarginBottom = 0;
VALA_EXTERN gchar* komorebi_on_screen_wallpaperName;

VALA_EXTERN void komorebi_utilities_applyCSS (GtkWidget** widgets,
                                  gint widgets_length1,
                                  const gchar* CSS);
VALA_EXTERN void komorebi_utilities_addAlpha (GtkWidget** widgets,
                                  gint widgets_length1);
VALA_EXTERN gchar* komorebi_utilities_formatDateTime (GDateTime* dateTime);
VALA_EXTERN void komorebi_utilities_readConfigurationFile (gint monitorNumber);
VALA_EXTERN void komorebi_utilities_updateConfigurationFile (void);
VALA_EXTERN void komorebi_utilities_fixConflicts (void);
VALA_EXTERN void komorebi_utilities_readWallpaperFile (void);
VALA_EXTERN void komorebi_utilities_createNewFolder (const gchar* name,
                                         gint number);
VALA_EXTERN gchar* komorebi_utilities_beautifyWallpaperName (const gchar* wallpaperName);
VALA_EXTERN gboolean komorebi_utilities_canPlayVideos (void);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);
static gssize _vala_array_length (gpointer array);

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

void
komorebi_utilities_applyCSS (GtkWidget** widgets,
                             gint widgets_length1,
                             const gchar* CSS)
{
	GtkCssProvider* Provider = NULL;
	GtkCssProvider* _tmp0_;
	GError* _inner_error0_ = NULL;
	g_return_if_fail (CSS != NULL);
	_tmp0_ = gtk_css_provider_new ();
	Provider = _tmp0_;
	gtk_css_provider_load_from_data (Provider, CSS, (gssize) -1, &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_object_unref0 (Provider);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	{
		GtkWidget** widget_collection = NULL;
		gint widget_collection_length1 = 0;
		gint _widget_collection_size_ = 0;
		gint widget_it = 0;
		widget_collection = widgets;
		widget_collection_length1 = widgets_length1;
		for (widget_it = 0; widget_it < widget_collection_length1; widget_it = widget_it + 1) {
			GtkWidget* _tmp1_;
			GtkWidget* widget = NULL;
			_tmp1_ = _g_object_ref0 (widget_collection[widget_it]);
			widget = _tmp1_;
			{
				GtkWidget* _tmp2_;
				GtkStyleContext* _tmp3_;
				_tmp2_ = widget;
				_tmp3_ = gtk_widget_get_style_context (_tmp2_);
				gtk_style_context_add_provider (_tmp3_, (GtkStyleProvider*) Provider, (guint) -1);
				_g_object_unref0 (widget);
			}
		}
	}
	_g_object_unref0 (Provider);
}

void
komorebi_utilities_addAlpha (GtkWidget** widgets,
                             gint widgets_length1)
{
	{
		GtkWidget** widget_collection = NULL;
		gint widget_collection_length1 = 0;
		gint _widget_collection_size_ = 0;
		gint widget_it = 0;
		widget_collection = widgets;
		widget_collection_length1 = widgets_length1;
		for (widget_it = 0; widget_it < widget_collection_length1; widget_it = widget_it + 1) {
			GtkWidget* _tmp0_;
			GtkWidget* widget = NULL;
			_tmp0_ = _g_object_ref0 (widget_collection[widget_it]);
			widget = _tmp0_;
			{
				GdkVisual* _tmp1_ = NULL;
				GtkWidget* _tmp2_;
				GdkScreen* _tmp3_;
				GdkVisual* _tmp4_;
				GtkWidget* _tmp8_;
				_tmp2_ = widget;
				_tmp3_ = gtk_widget_get_screen (_tmp2_);
				_tmp4_ = gdk_screen_get_rgba_visual (_tmp3_);
				_tmp1_ = _tmp4_;
				if (_tmp1_ == NULL) {
					GtkWidget* _tmp5_;
					GdkScreen* _tmp6_;
					GdkVisual* _tmp7_;
					_tmp5_ = widget;
					_tmp6_ = gtk_widget_get_screen (_tmp5_);
					_tmp7_ = gdk_screen_get_system_visual (_tmp6_);
					_tmp1_ = _tmp7_;
				}
				_tmp8_ = widget;
				gtk_widget_set_visual (_tmp8_, _tmp1_);
				_g_object_unref0 (widget);
			}
		}
	}
}

gchar*
komorebi_utilities_formatDateTime (GDateTime* dateTime)
{
	gchar* _tmp0_;
	gchar* result;
	g_return_val_if_fail (dateTime != NULL, NULL);
	_tmp0_ = g_date_time_format (dateTime, "%m/%d/%Y %H:%M");
	result = _tmp0_;
	return result;
}

void
komorebi_utilities_readConfigurationFile (gint monitorNumber)
{
	gchar* _tmp0_;
	const gchar* _tmp1_;
	GFile* _tmp10_;
	GKeyFile* _tmp13_;
	GFile* _tmp15_;
	GKeyFile* _tmp16_;
	const gchar* _tmp17_;
	gchar* key_file_group = NULL;
	gchar* _tmp18_;
	gboolean _tmp19_ = FALSE;
	GKeyFile* _tmp20_;
	const gchar* _tmp21_;
	gchar* _tmp25_ = NULL;
	GKeyFile* _tmp26_;
	const gchar* _tmp27_;
	gchar* _tmp28_;
	gchar* _tmp29_;
	GError* _inner_error0_ = NULL;
	_tmp0_ = g_strdup ("bw-girl");
	_g_free0 (komorebi_on_screen_wallpaperName);
	komorebi_on_screen_wallpaperName = _tmp0_;
	_tmp1_ = komorebi_utilities_configFilePath;
	if (_tmp1_ == NULL) {
		const gchar* _tmp2_;
		gchar* _tmp3_;
		gchar* _tmp4_;
		gchar* _tmp5_;
		gchar* _tmp6_;
		gchar* _tmp7_;
		gchar* _tmp8_;
		gchar* _tmp9_;
		_tmp2_ = g_get_home_dir ();
		_tmp3_ = g_strconcat (_tmp2_, "/.Komorebi", NULL);
		_tmp4_ = _tmp3_;
		_tmp5_ = g_strdup_printf ("%i", monitorNumber);
		_tmp6_ = _tmp5_;
		_tmp7_ = g_strconcat (_tmp4_, _tmp6_, NULL);
		_tmp8_ = _tmp7_;
		_tmp9_ = g_strconcat (_tmp8_, ".prop", NULL);
		_g_free0 (komorebi_utilities_configFilePath);
		komorebi_utilities_configFilePath = _tmp9_;
		_g_free0 (_tmp8_);
		_g_free0 (_tmp6_);
		_g_free0 (_tmp4_);
	}
	_tmp10_ = komorebi_utilities_configFile;
	if (_tmp10_ == NULL) {
		const gchar* _tmp11_;
		GFile* _tmp12_;
		_tmp11_ = komorebi_utilities_configFilePath;
		_tmp12_ = g_file_new_for_path (_tmp11_);
		_g_object_unref0 (komorebi_utilities_configFile);
		komorebi_utilities_configFile = _tmp12_;
	}
	_tmp13_ = komorebi_utilities_configKeyFile;
	if (_tmp13_ == NULL) {
		GKeyFile* _tmp14_;
		_tmp14_ = g_key_file_new ();
		_g_key_file_unref0 (komorebi_utilities_configKeyFile);
		komorebi_utilities_configKeyFile = _tmp14_;
	}
	_tmp15_ = komorebi_utilities_configFile;
	if (!g_file_query_exists (_tmp15_, NULL)) {
		g_print ("No configuration file found. Creating one..\n");
		komorebi_utilities_updateConfigurationFile ();
		return;
	}
	g_print ("Reading config file..\n");
	_tmp16_ = komorebi_utilities_configKeyFile;
	_tmp17_ = komorebi_utilities_configFilePath;
	g_key_file_load_from_file (_tmp16_, _tmp17_, G_KEY_FILE_NONE, &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_tmp18_ = g_strdup ("KomorebiProperties");
	key_file_group = _tmp18_;
	_tmp20_ = komorebi_utilities_configKeyFile;
	_tmp21_ = key_file_group;
	if (!g_key_file_has_group (_tmp20_, _tmp21_)) {
		_tmp19_ = TRUE;
	} else {
		gboolean _tmp22_ = FALSE;
		GKeyFile* _tmp23_;
		const gchar* _tmp24_;
		_tmp23_ = komorebi_utilities_configKeyFile;
		_tmp24_ = key_file_group;
		_tmp22_ = g_key_file_has_key (_tmp23_, _tmp24_, "WallpaperName", &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_free0 (key_file_group);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return;
		}
		_tmp19_ = !_tmp22_;
	}
	if (_tmp19_) {
		g_print ("[WARNING]: invalid configuration file found. Fixing..\n");
		komorebi_utilities_updateConfigurationFile ();
		_g_free0 (key_file_group);
		return;
	}
	_tmp26_ = komorebi_utilities_configKeyFile;
	_tmp27_ = key_file_group;
	_tmp28_ = g_key_file_get_string (_tmp26_, _tmp27_, "WallpaperName", &_inner_error0_);
	_tmp25_ = _tmp28_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (key_file_group);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_tmp29_ = _tmp25_;
	_tmp25_ = NULL;
	_g_free0 (komorebi_on_screen_wallpaperName);
	komorebi_on_screen_wallpaperName = _tmp29_;
	komorebi_utilities_fixConflicts ();
	_g_free0 (_tmp25_);
	_g_free0 (key_file_group);
}

void
komorebi_utilities_updateConfigurationFile (void)
{
	gchar* key_file_group = NULL;
	gchar* _tmp0_;
	GKeyFile* _tmp1_;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	GFile* _tmp4_;
	GFileOutputStream* _tmp6_ = NULL;
	GFile* _tmp7_;
	GFileOutputStream* _tmp8_;
	GDataOutputStream* stream = NULL;
	GDataOutputStream* _tmp9_;
	GDataOutputStream* _tmp10_;
	GKeyFile* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	GDataOutputStream* _tmp14_;
	GError* _inner_error0_ = NULL;
	_tmp0_ = g_strdup ("KomorebiProperties");
	key_file_group = _tmp0_;
	_tmp1_ = komorebi_utilities_configKeyFile;
	_tmp2_ = key_file_group;
	_tmp3_ = komorebi_on_screen_wallpaperName;
	g_key_file_set_string (_tmp1_, _tmp2_, "WallpaperName", _tmp3_);
	_tmp4_ = komorebi_utilities_configFile;
	if (g_file_query_exists (_tmp4_, NULL)) {
		GFile* _tmp5_;
		_tmp5_ = komorebi_utilities_configFile;
		g_file_delete (_tmp5_, NULL, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_free0 (key_file_group);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return;
		}
	}
	_tmp7_ = komorebi_utilities_configFile;
	_tmp8_ = g_file_create (_tmp7_, 0, NULL, &_inner_error0_);
	_tmp6_ = _tmp8_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (key_file_group);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_tmp9_ = g_data_output_stream_new ((GOutputStream*) _tmp6_);
	stream = _tmp9_;
	_tmp10_ = stream;
	_tmp11_ = komorebi_utilities_configKeyFile;
	_tmp12_ = g_key_file_to_data (_tmp11_, NULL, NULL);
	_tmp13_ = _tmp12_;
	g_data_output_stream_put_string (_tmp10_, _tmp13_, NULL, &_inner_error0_);
	_g_free0 (_tmp13_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_object_unref0 (stream);
		_g_object_unref0 (_tmp6_);
		_g_free0 (key_file_group);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_tmp14_ = stream;
	g_output_stream_close ((GOutputStream*) _tmp14_, NULL, &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_object_unref0 (stream);
		_g_object_unref0 (_tmp6_);
		_g_free0 (key_file_group);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_g_object_unref0 (stream);
	_g_object_unref0 (_tmp6_);
	_g_free0 (key_file_group);
}

void
komorebi_utilities_fixConflicts (void)
{
	GSettings* _tmp0_;
	GSettings* _tmp1_;
	GSettingsSchemaSource* settingsSchemaSource = NULL;
	GSettingsSchemaSource* _tmp2_;
	GSettingsSchema* settingsSchema = NULL;
	GSettingsSchema* _tmp3_;
	GSettingsSchema* _tmp4_;
	GError* _inner_error0_ = NULL;
	_tmp0_ = g_settings_new ("org.gnome.desktop.background");
	_tmp1_ = _tmp0_;
	g_settings_set_boolean (_tmp1_, "show-desktop-icons", FALSE);
	_g_object_unref0 (_tmp1_);
	_tmp2_ = g_settings_schema_source_new_from_directory ("/usr/share/glib-2.0/schemas", NULL, FALSE, &_inner_error0_);
	settingsSchemaSource = _tmp2_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_tmp3_ = g_settings_schema_source_lookup (settingsSchemaSource, "org.nemo.desktop", FALSE);
	settingsSchema = _tmp3_;
	_tmp4_ = settingsSchema;
	if (_tmp4_ != NULL) {
		GSettings* _tmp5_;
		GSettings* _tmp6_;
		_tmp5_ = g_settings_new ("org.nemo.desktop");
		_tmp6_ = _tmp5_;
		g_settings_set_boolean (_tmp6_, "show-desktop-icons", FALSE);
		_g_object_unref0 (_tmp6_);
	}
	_g_settings_schema_unref0 (settingsSchema);
	_g_settings_schema_source_unref0 (settingsSchemaSource);
}

static const gchar*
string_to_string (const gchar* self)
{
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}

void
komorebi_utilities_readWallpaperFile (void)
{
	gchar* wallpaperPath = NULL;
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* wallpaperConfigPath = NULL;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	gchar* _tmp5_;
	gboolean _tmp6_ = FALSE;
	gboolean _tmp7_ = FALSE;
	const gchar* _tmp8_;
	GKeyFile* _tmp26_;
	GKeyFile* _tmp28_;
	const gchar* _tmp29_;
	gchar* _tmp30_ = NULL;
	GKeyFile* _tmp31_;
	gchar* _tmp32_;
	gchar* _tmp33_;
	gboolean _tmp34_ = FALSE;
	GKeyFile* _tmp35_;
	gboolean _tmp36_ = FALSE;
	GKeyFile* _tmp37_;
	gint _tmp38_ = 0;
	GKeyFile* _tmp39_;
	gint _tmp40_ = 0;
	GKeyFile* _tmp41_;
	gint _tmp42_ = 0;
	GKeyFile* _tmp43_;
	gint _tmp44_ = 0;
	GKeyFile* _tmp45_;
	gdouble _tmp46_ = 0.0;
	GKeyFile* _tmp47_;
	gdouble _tmp48_ = 0.0;
	GKeyFile* _tmp49_;
	gdouble _tmp50_ = 0.0;
	GKeyFile* _tmp51_;
	gchar* _tmp52_ = NULL;
	GKeyFile* _tmp53_;
	gchar* _tmp54_;
	gchar* _tmp55_;
	gchar* _tmp56_ = NULL;
	GKeyFile* _tmp57_;
	gchar* _tmp58_;
	gchar* _tmp59_;
	gboolean _tmp60_ = FALSE;
	GKeyFile* _tmp61_;
	gchar* _tmp62_ = NULL;
	GKeyFile* _tmp63_;
	gchar* _tmp64_;
	gchar* _tmp65_;
	gint _tmp66_ = 0;
	GKeyFile* _tmp67_;
	gchar* _tmp68_ = NULL;
	GKeyFile* _tmp69_;
	gchar* _tmp70_;
	gchar* _tmp71_;
	gint _tmp72_ = 0;
	GKeyFile* _tmp73_;
	gchar* _tmp74_ = NULL;
	GKeyFile* _tmp75_;
	gchar* _tmp76_;
	gchar* _tmp77_;
	gchar* _tmp78_ = NULL;
	GKeyFile* _tmp79_;
	gchar* _tmp80_;
	gchar* _tmp81_;
	const gchar* _tmp82_;
	const gchar* _tmp87_;
	gboolean _tmp92_ = FALSE;
	GKeyFile* _tmp93_;
	gboolean _tmp94_ = FALSE;
	GKeyFile* _tmp95_;
	gchar* _tmp96_ = NULL;
	GKeyFile* _tmp97_;
	gchar* _tmp98_;
	gchar* _tmp99_;
	gint _tmp100_ = 0;
	GKeyFile* _tmp101_;
	gint _tmp102_ = 0;
	GKeyFile* _tmp103_;
	gint _tmp104_ = 0;
	GKeyFile* _tmp105_;
	gchar* wallpaperJpgPath = NULL;
	const gchar* _tmp106_;
	const gchar* _tmp107_;
	gchar* _tmp108_;
	GSettings* _tmp109_;
	GSettings* _tmp110_;
	const gchar* _tmp111_;
	gchar* _tmp112_;
	gchar* _tmp113_;
	GSettings* _tmp114_;
	GSettings* _tmp115_;
	GError* _inner_error0_ = NULL;
	_tmp0_ = komorebi_on_screen_wallpaperName;
	_tmp1_ = string_to_string (_tmp0_);
	_tmp2_ = g_strconcat ("/System/Resources/Komorebi/", _tmp1_, NULL);
	wallpaperPath = _tmp2_;
	_tmp3_ = wallpaperPath;
	_tmp4_ = string_to_string (_tmp3_);
	_tmp5_ = g_strconcat (_tmp4_, "/config", NULL);
	wallpaperConfigPath = _tmp5_;
	_tmp8_ = komorebi_on_screen_wallpaperName;
	if (_tmp8_ == NULL) {
		_tmp7_ = TRUE;
	} else {
		const gchar* _tmp9_;
		GFile* _tmp10_;
		GFile* _tmp11_;
		_tmp9_ = wallpaperPath;
		_tmp10_ = g_file_new_for_path (_tmp9_);
		_tmp11_ = _tmp10_;
		_tmp7_ = !g_file_query_exists (_tmp11_, NULL);
		_g_object_unref0 (_tmp11_);
	}
	if (_tmp7_) {
		_tmp6_ = TRUE;
	} else {
		const gchar* _tmp12_;
		GFile* _tmp13_;
		GFile* _tmp14_;
		_tmp12_ = wallpaperConfigPath;
		_tmp13_ = g_file_new_for_path (_tmp12_);
		_tmp14_ = _tmp13_;
		_tmp6_ = !g_file_query_exists (_tmp14_, NULL);
		_g_object_unref0 (_tmp14_);
	}
	if (_tmp6_) {
		gchar* _tmp15_;
		const gchar* _tmp16_;
		const gchar* _tmp17_;
		gchar* _tmp18_;
		const gchar* _tmp19_;
		const gchar* _tmp20_;
		gchar* _tmp21_;
		const gchar* _tmp22_;
		const gchar* _tmp23_;
		gchar* _tmp24_;
		gchar* _tmp25_;
		_tmp15_ = g_strdup ("foggy_sunny_mountain");
		_g_free0 (komorebi_on_screen_wallpaperName);
		komorebi_on_screen_wallpaperName = _tmp15_;
		_tmp16_ = komorebi_on_screen_wallpaperName;
		_tmp17_ = string_to_string (_tmp16_);
		_tmp18_ = g_strconcat ("/System/Resources/Komorebi/", _tmp17_, NULL);
		_g_free0 (wallpaperPath);
		wallpaperPath = _tmp18_;
		_tmp19_ = wallpaperPath;
		_tmp20_ = string_to_string (_tmp19_);
		_tmp21_ = g_strconcat (_tmp20_, "/config", NULL);
		_g_free0 (wallpaperConfigPath);
		wallpaperConfigPath = _tmp21_;
		_tmp22_ = komorebi_on_screen_wallpaperName;
		_tmp23_ = string_to_string (_tmp22_);
		_tmp24_ = g_strconcat ("[ERROR]: got an invalid wallpaper. Setting to default: ", _tmp23_, "\n", NULL);
		_tmp25_ = _tmp24_;
		g_print ("%s", _tmp25_);
		_g_free0 (_tmp25_);
	}
	_tmp26_ = komorebi_utilities_wallpaperKeyFile;
	if (_tmp26_ == NULL) {
		GKeyFile* _tmp27_;
		_tmp27_ = g_key_file_new ();
		_g_key_file_unref0 (komorebi_utilities_wallpaperKeyFile);
		komorebi_utilities_wallpaperKeyFile = _tmp27_;
	}
	_tmp28_ = komorebi_utilities_wallpaperKeyFile;
	_tmp29_ = wallpaperConfigPath;
	g_key_file_load_from_file (_tmp28_, _tmp29_, G_KEY_FILE_NONE, &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_tmp31_ = komorebi_utilities_wallpaperKeyFile;
	_tmp32_ = g_key_file_get_string (_tmp31_, "Info", "WallpaperType", &_inner_error0_);
	_tmp30_ = _tmp32_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_tmp33_ = _tmp30_;
	_tmp30_ = NULL;
	_g_free0 (komorebi_utilities_wallpaperType);
	komorebi_utilities_wallpaperType = _tmp33_;
	_tmp35_ = komorebi_utilities_wallpaperKeyFile;
	_tmp34_ = g_key_file_get_boolean (_tmp35_, "DateTime", "Visible", &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (_tmp30_);
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	komorebi_utilities_dateTimeVisible = _tmp34_;
	_tmp37_ = komorebi_utilities_wallpaperKeyFile;
	_tmp36_ = g_key_file_get_boolean (_tmp37_, "DateTime", "Parallax", &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (_tmp30_);
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	komorebi_utilities_dateTimeParallax = _tmp36_;
	_tmp39_ = komorebi_utilities_wallpaperKeyFile;
	_tmp38_ = g_key_file_get_integer (_tmp39_, "DateTime", "MarginLeft", &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (_tmp30_);
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	komorebi_utilities_dateTimeMarginLeft = _tmp38_;
	_tmp41_ = komorebi_utilities_wallpaperKeyFile;
	_tmp40_ = g_key_file_get_integer (_tmp41_, "DateTime", "MarginTop", &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (_tmp30_);
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	komorebi_utilities_dateTimeMarginTop = _tmp40_;
	_tmp43_ = komorebi_utilities_wallpaperKeyFile;
	_tmp42_ = g_key_file_get_integer (_tmp43_, "DateTime", "MarginBottom", &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (_tmp30_);
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	komorebi_utilities_dateTimeMarginBottom = _tmp42_;
	_tmp45_ = komorebi_utilities_wallpaperKeyFile;
	_tmp44_ = g_key_file_get_integer (_tmp45_, "DateTime", "MarginRight", &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (_tmp30_);
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	komorebi_utilities_dateTimeMarginRight = _tmp44_;
	_tmp47_ = komorebi_utilities_wallpaperKeyFile;
	_tmp46_ = g_key_file_get_double (_tmp47_, "DateTime", "RotationX", &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (_tmp30_);
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	komorebi_utilities_dateTimeRotationX = _tmp46_;
	_tmp49_ = komorebi_utilities_wallpaperKeyFile;
	_tmp48_ = g_key_file_get_double (_tmp49_, "DateTime", "RotationY", &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (_tmp30_);
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	komorebi_utilities_dateTimeRotationY = _tmp48_;
	_tmp51_ = komorebi_utilities_wallpaperKeyFile;
	_tmp50_ = g_key_file_get_double (_tmp51_, "DateTime", "RotationZ", &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (_tmp30_);
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	komorebi_utilities_dateTimeRotationZ = _tmp50_;
	_tmp53_ = komorebi_utilities_wallpaperKeyFile;
	_tmp54_ = g_key_file_get_string (_tmp53_, "DateTime", "Position", &_inner_error0_);
	_tmp52_ = _tmp54_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (_tmp30_);
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_tmp55_ = _tmp52_;
	_tmp52_ = NULL;
	_g_free0 (komorebi_utilities_dateTimePosition);
	komorebi_utilities_dateTimePosition = _tmp55_;
	_tmp57_ = komorebi_utilities_wallpaperKeyFile;
	_tmp58_ = g_key_file_get_string (_tmp57_, "DateTime", "Alignment", &_inner_error0_);
	_tmp56_ = _tmp58_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (_tmp52_);
		_g_free0 (_tmp30_);
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_tmp59_ = _tmp56_;
	_tmp56_ = NULL;
	_g_free0 (komorebi_utilities_dateTimeAlignment);
	komorebi_utilities_dateTimeAlignment = _tmp59_;
	_tmp61_ = komorebi_utilities_wallpaperKeyFile;
	_tmp60_ = g_key_file_get_boolean (_tmp61_, "DateTime", "AlwaysOnTop", &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (_tmp56_);
		_g_free0 (_tmp52_);
		_g_free0 (_tmp30_);
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	komorebi_utilities_dateTimeAlwaysOnTop = _tmp60_;
	_tmp63_ = komorebi_utilities_wallpaperKeyFile;
	_tmp64_ = g_key_file_get_string (_tmp63_, "DateTime", "Color", &_inner_error0_);
	_tmp62_ = _tmp64_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (_tmp56_);
		_g_free0 (_tmp52_);
		_g_free0 (_tmp30_);
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_tmp65_ = _tmp62_;
	_tmp62_ = NULL;
	_g_free0 (komorebi_utilities_dateTimeColor);
	komorebi_utilities_dateTimeColor = _tmp65_;
	_tmp67_ = komorebi_utilities_wallpaperKeyFile;
	_tmp66_ = g_key_file_get_integer (_tmp67_, "DateTime", "Alpha", &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (_tmp62_);
		_g_free0 (_tmp56_);
		_g_free0 (_tmp52_);
		_g_free0 (_tmp30_);
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	komorebi_utilities_dateTimeAlpha = _tmp66_;
	_tmp69_ = komorebi_utilities_wallpaperKeyFile;
	_tmp70_ = g_key_file_get_string (_tmp69_, "DateTime", "ShadowColor", &_inner_error0_);
	_tmp68_ = _tmp70_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (_tmp62_);
		_g_free0 (_tmp56_);
		_g_free0 (_tmp52_);
		_g_free0 (_tmp30_);
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_tmp71_ = _tmp68_;
	_tmp68_ = NULL;
	_g_free0 (komorebi_utilities_dateTimeShadowColor);
	komorebi_utilities_dateTimeShadowColor = _tmp71_;
	_tmp73_ = komorebi_utilities_wallpaperKeyFile;
	_tmp72_ = g_key_file_get_integer (_tmp73_, "DateTime", "ShadowAlpha", &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (_tmp68_);
		_g_free0 (_tmp62_);
		_g_free0 (_tmp56_);
		_g_free0 (_tmp52_);
		_g_free0 (_tmp30_);
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	komorebi_utilities_dateTimeShadowAlpha = _tmp72_;
	_tmp75_ = komorebi_utilities_wallpaperKeyFile;
	_tmp76_ = g_key_file_get_string (_tmp75_, "DateTime", "TimeFont", &_inner_error0_);
	_tmp74_ = _tmp76_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (_tmp68_);
		_g_free0 (_tmp62_);
		_g_free0 (_tmp56_);
		_g_free0 (_tmp52_);
		_g_free0 (_tmp30_);
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_tmp77_ = _tmp74_;
	_tmp74_ = NULL;
	_g_free0 (komorebi_utilities_dateTimeTimeFont);
	komorebi_utilities_dateTimeTimeFont = _tmp77_;
	_tmp79_ = komorebi_utilities_wallpaperKeyFile;
	_tmp80_ = g_key_file_get_string (_tmp79_, "DateTime", "DateFont", &_inner_error0_);
	_tmp78_ = _tmp80_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (_tmp74_);
		_g_free0 (_tmp68_);
		_g_free0 (_tmp62_);
		_g_free0 (_tmp56_);
		_g_free0 (_tmp52_);
		_g_free0 (_tmp30_);
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_tmp81_ = _tmp78_;
	_tmp78_ = NULL;
	_g_free0 (komorebi_utilities_dateTimeDateFont);
	komorebi_utilities_dateTimeDateFont = _tmp81_;
	_tmp82_ = komorebi_utilities_wallpaperType;
	if (g_strcmp0 (_tmp82_, "video") == 0) {
		gchar* _tmp83_ = NULL;
		GKeyFile* _tmp84_;
		gchar* _tmp85_;
		gchar* _tmp86_;
		_tmp84_ = komorebi_utilities_wallpaperKeyFile;
		_tmp85_ = g_key_file_get_string (_tmp84_, "Info", "VideoFileName", &_inner_error0_);
		_tmp83_ = _tmp85_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_free0 (_tmp78_);
			_g_free0 (_tmp74_);
			_g_free0 (_tmp68_);
			_g_free0 (_tmp62_);
			_g_free0 (_tmp56_);
			_g_free0 (_tmp52_);
			_g_free0 (_tmp30_);
			_g_free0 (wallpaperConfigPath);
			_g_free0 (wallpaperPath);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return;
		}
		_tmp86_ = _tmp83_;
		_tmp83_ = NULL;
		_g_free0 (komorebi_utilities_videoFileName);
		komorebi_utilities_videoFileName = _tmp86_;
		komorebi_utilities_assetVisible = FALSE;
		komorebi_utilities_wallpaperParallax = komorebi_utilities_assetVisible;
		_g_free0 (_tmp83_);
		_g_free0 (_tmp78_);
		_g_free0 (_tmp74_);
		_g_free0 (_tmp68_);
		_g_free0 (_tmp62_);
		_g_free0 (_tmp56_);
		_g_free0 (_tmp52_);
		_g_free0 (_tmp30_);
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		return;
	}
	_tmp87_ = komorebi_utilities_wallpaperType;
	if (g_strcmp0 (_tmp87_, "web_page") == 0) {
		gchar* _tmp88_ = NULL;
		GKeyFile* _tmp89_;
		gchar* _tmp90_;
		gchar* _tmp91_;
		_tmp89_ = komorebi_utilities_wallpaperKeyFile;
		_tmp90_ = g_key_file_get_string (_tmp89_, "Info", "WebPageUrl", &_inner_error0_);
		_tmp88_ = _tmp90_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_free0 (_tmp78_);
			_g_free0 (_tmp74_);
			_g_free0 (_tmp68_);
			_g_free0 (_tmp62_);
			_g_free0 (_tmp56_);
			_g_free0 (_tmp52_);
			_g_free0 (_tmp30_);
			_g_free0 (wallpaperConfigPath);
			_g_free0 (wallpaperPath);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return;
		}
		_tmp91_ = _tmp88_;
		_tmp88_ = NULL;
		_g_free0 (komorebi_utilities_webPageUrl);
		komorebi_utilities_webPageUrl = _tmp91_;
		komorebi_utilities_assetVisible = FALSE;
		komorebi_utilities_wallpaperParallax = komorebi_utilities_assetVisible;
		_g_free0 (_tmp88_);
		_g_free0 (_tmp78_);
		_g_free0 (_tmp74_);
		_g_free0 (_tmp68_);
		_g_free0 (_tmp62_);
		_g_free0 (_tmp56_);
		_g_free0 (_tmp52_);
		_g_free0 (_tmp30_);
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		return;
	}
	_tmp93_ = komorebi_utilities_wallpaperKeyFile;
	_tmp92_ = g_key_file_get_boolean (_tmp93_, "Wallpaper", "Parallax", &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (_tmp78_);
		_g_free0 (_tmp74_);
		_g_free0 (_tmp68_);
		_g_free0 (_tmp62_);
		_g_free0 (_tmp56_);
		_g_free0 (_tmp52_);
		_g_free0 (_tmp30_);
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	komorebi_utilities_wallpaperParallax = _tmp92_;
	_tmp95_ = komorebi_utilities_wallpaperKeyFile;
	_tmp94_ = g_key_file_get_boolean (_tmp95_, "Asset", "Visible", &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (_tmp78_);
		_g_free0 (_tmp74_);
		_g_free0 (_tmp68_);
		_g_free0 (_tmp62_);
		_g_free0 (_tmp56_);
		_g_free0 (_tmp52_);
		_g_free0 (_tmp30_);
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	komorebi_utilities_assetVisible = _tmp94_;
	_tmp97_ = komorebi_utilities_wallpaperKeyFile;
	_tmp98_ = g_key_file_get_string (_tmp97_, "Asset", "AnimationMode", &_inner_error0_);
	_tmp96_ = _tmp98_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (_tmp78_);
		_g_free0 (_tmp74_);
		_g_free0 (_tmp68_);
		_g_free0 (_tmp62_);
		_g_free0 (_tmp56_);
		_g_free0 (_tmp52_);
		_g_free0 (_tmp30_);
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_tmp99_ = _tmp96_;
	_tmp96_ = NULL;
	_g_free0 (komorebi_utilities_assetAnimationMode);
	komorebi_utilities_assetAnimationMode = _tmp99_;
	_tmp101_ = komorebi_utilities_wallpaperKeyFile;
	_tmp100_ = g_key_file_get_integer (_tmp101_, "Asset", "AnimationSpeed", &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (_tmp96_);
		_g_free0 (_tmp78_);
		_g_free0 (_tmp74_);
		_g_free0 (_tmp68_);
		_g_free0 (_tmp62_);
		_g_free0 (_tmp56_);
		_g_free0 (_tmp52_);
		_g_free0 (_tmp30_);
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	komorebi_utilities_assetAnimationSpeed = _tmp100_;
	_tmp103_ = komorebi_utilities_wallpaperKeyFile;
	_tmp102_ = g_key_file_get_integer (_tmp103_, "Asset", "Width", &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (_tmp96_);
		_g_free0 (_tmp78_);
		_g_free0 (_tmp74_);
		_g_free0 (_tmp68_);
		_g_free0 (_tmp62_);
		_g_free0 (_tmp56_);
		_g_free0 (_tmp52_);
		_g_free0 (_tmp30_);
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	komorebi_utilities_assetWidth = _tmp102_;
	_tmp105_ = komorebi_utilities_wallpaperKeyFile;
	_tmp104_ = g_key_file_get_integer (_tmp105_, "Asset", "Height", &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (_tmp96_);
		_g_free0 (_tmp78_);
		_g_free0 (_tmp74_);
		_g_free0 (_tmp68_);
		_g_free0 (_tmp62_);
		_g_free0 (_tmp56_);
		_g_free0 (_tmp52_);
		_g_free0 (_tmp30_);
		_g_free0 (wallpaperConfigPath);
		_g_free0 (wallpaperPath);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	komorebi_utilities_assetHeight = _tmp104_;
	_tmp106_ = komorebi_on_screen_wallpaperName;
	_tmp107_ = string_to_string (_tmp106_);
	_tmp108_ = g_strconcat ("/System/Resources/Komorebi/", _tmp107_, "/wallpaper.jpg", NULL);
	wallpaperJpgPath = _tmp108_;
	_tmp109_ = g_settings_new ("org.gnome.desktop.background");
	_tmp110_ = _tmp109_;
	_tmp111_ = wallpaperJpgPath;
	_tmp112_ = g_strconcat ("file://", _tmp111_, NULL);
	_tmp113_ = _tmp112_;
	g_settings_set_string (_tmp110_, "picture-uri", _tmp113_);
	_g_free0 (_tmp113_);
	_g_object_unref0 (_tmp110_);
	_tmp114_ = g_settings_new ("org.gnome.desktop.background");
	_tmp115_ = _tmp114_;
	g_settings_set_string (_tmp115_, "picture-options", "stretched");
	_g_object_unref0 (_tmp115_);
	_g_free0 (wallpaperJpgPath);
	_g_free0 (_tmp96_);
	_g_free0 (_tmp78_);
	_g_free0 (_tmp74_);
	_g_free0 (_tmp68_);
	_g_free0 (_tmp62_);
	_g_free0 (_tmp56_);
	_g_free0 (_tmp52_);
	_g_free0 (_tmp30_);
	_g_free0 (wallpaperConfigPath);
	_g_free0 (wallpaperPath);
}

void
komorebi_utilities_createNewFolder (const gchar* name,
                                    gint number)
{
	GFile* newFolder = NULL;
	GFile* _tmp17_;
	g_return_if_fail (name != NULL);
	if (number > 0) {
		const gchar* _tmp0_;
		const gchar* _tmp1_;
		gchar* _tmp2_;
		gchar* _tmp3_;
		const gchar* _tmp4_;
		gchar* _tmp5_;
		gchar* _tmp6_;
		gchar* _tmp7_;
		gchar* _tmp8_;
		GFile* _tmp9_;
		_tmp0_ = komorebi_utilities_desktopPath;
		_tmp1_ = string_to_string (name);
		_tmp2_ = g_strdup_printf ("%i", number);
		_tmp3_ = _tmp2_;
		_tmp4_ = string_to_string (_tmp3_);
		_tmp5_ = g_strconcat ("/", _tmp1_, " (", _tmp4_, ")", NULL);
		_tmp6_ = _tmp5_;
		_tmp7_ = g_strconcat (_tmp0_, _tmp6_, NULL);
		_tmp8_ = _tmp7_;
		_tmp9_ = g_file_new_for_path (_tmp8_);
		_g_object_unref0 (newFolder);
		newFolder = _tmp9_;
		_g_free0 (_tmp8_);
		_g_free0 (_tmp6_);
		_g_free0 (_tmp3_);
	} else {
		const gchar* _tmp10_;
		const gchar* _tmp11_;
		gchar* _tmp12_;
		gchar* _tmp13_;
		gchar* _tmp14_;
		gchar* _tmp15_;
		GFile* _tmp16_;
		_tmp10_ = komorebi_utilities_desktopPath;
		_tmp11_ = string_to_string (name);
		_tmp12_ = g_strconcat ("/", _tmp11_, NULL);
		_tmp13_ = _tmp12_;
		_tmp14_ = g_strconcat (_tmp10_, _tmp13_, NULL);
		_tmp15_ = _tmp14_;
		_tmp16_ = g_file_new_for_path (_tmp15_);
		_g_object_unref0 (newFolder);
		newFolder = _tmp16_;
		_g_free0 (_tmp15_);
		_g_free0 (_tmp13_);
	}
	_tmp17_ = newFolder;
	if (g_file_query_exists (_tmp17_, NULL)) {
		komorebi_utilities_createNewFolder (name, number + 1);
	} else {
		GFile* _tmp18_;
		_tmp18_ = newFolder;
		g_file_make_directory_async (_tmp18_, G_PRIORITY_DEFAULT, NULL, NULL, NULL);
	}
	_g_object_unref0 (newFolder);
}

static gchar
string_get (const gchar* self,
            glong index)
{
	gchar _tmp0_;
	gchar result;
	g_return_val_if_fail (self != NULL, '\0');
	_tmp0_ = ((gchar*) self)[index];
	result = _tmp0_;
	return result;
}

static glong
string_strnlen (gchar* str,
                glong maxlen)
{
	gchar* end = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	glong result;
	_tmp0_ = memchr (str, 0, (gsize) maxlen);
	end = _tmp0_;
	_tmp1_ = end;
	if (_tmp1_ == NULL) {
		result = maxlen;
		return result;
	} else {
		gchar* _tmp2_;
		_tmp2_ = end;
		result = (glong) (_tmp2_ - str);
		return result;
	}
}

static gchar*
string_substring (const gchar* self,
                  glong offset,
                  glong len)
{
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	gchar* _tmp3_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	if (offset >= ((glong) 0)) {
		_tmp0_ = len >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		string_length = string_strnlen ((gchar*) self, offset + len);
	} else {
		gint _tmp1_;
		gint _tmp2_;
		_tmp1_ = strlen (self);
		_tmp2_ = _tmp1_;
		string_length = (glong) _tmp2_;
	}
	if (offset < ((glong) 0)) {
		offset = string_length + offset;
		g_return_val_if_fail (offset >= ((glong) 0), NULL);
	} else {
		g_return_val_if_fail (offset <= string_length, NULL);
	}
	if (len < ((glong) 0)) {
		len = string_length - offset;
	}
	g_return_val_if_fail ((offset + len) <= string_length, NULL);
	_tmp3_ = g_strndup (((gchar*) self) + offset, (gsize) len);
	result = _tmp3_;
	return result;
}

gchar*
komorebi_utilities_beautifyWallpaperName (const gchar* wallpaperName)
{
	gchar* resultString = NULL;
	gchar* _tmp0_;
	gchar** _tmp1_;
	gchar** _tmp2_;
	gchar* result;
	g_return_val_if_fail (wallpaperName != NULL, NULL);
	_tmp0_ = g_strdup ("");
	resultString = _tmp0_;
	_tmp2_ = _tmp1_ = g_strsplit (wallpaperName, "_", 0);
	{
		gchar** word_collection = NULL;
		gint word_collection_length1 = 0;
		gint _word_collection_size_ = 0;
		gint word_it = 0;
		word_collection = _tmp2_;
		word_collection_length1 = _vala_array_length (_tmp1_);
		for (word_it = 0; word_it < word_collection_length1; word_it = word_it + 1) {
			gchar* _tmp3_;
			gchar* word = NULL;
			_tmp3_ = g_strdup (word_collection[word_it]);
			word = _tmp3_;
			{
				const gchar* _tmp4_;
				const gchar* _tmp5_;
				gchar* _tmp6_;
				gchar* _tmp7_;
				gchar* _tmp8_;
				gchar* _tmp9_;
				const gchar* _tmp10_;
				gchar* _tmp11_;
				gchar* _tmp12_;
				gchar* _tmp13_;
				gchar* _tmp14_;
				gchar* _tmp15_;
				gchar* _tmp16_;
				gchar* _tmp17_;
				gchar* _tmp18_;
				gchar* _tmp19_;
				_tmp4_ = resultString;
				_tmp5_ = word;
				_tmp6_ = g_strdup_printf ("%c", string_get (_tmp5_, (glong) 0));
				_tmp7_ = _tmp6_;
				_tmp8_ = g_utf8_strup (_tmp7_, (gssize) -1);
				_tmp9_ = _tmp8_;
				_tmp10_ = word;
				_tmp11_ = string_substring (_tmp10_, (glong) 1, (glong) -1);
				_tmp12_ = _tmp11_;
				_tmp13_ = g_utf8_strdown (_tmp12_, (gssize) -1);
				_tmp14_ = _tmp13_;
				_tmp15_ = g_strconcat (_tmp9_, _tmp14_, NULL);
				_tmp16_ = _tmp15_;
				_tmp17_ = g_strconcat (_tmp16_, " ", NULL);
				_tmp18_ = _tmp17_;
				_tmp19_ = g_strconcat (_tmp4_, _tmp18_, NULL);
				_g_free0 (resultString);
				resultString = _tmp19_;
				_g_free0 (_tmp18_);
				_g_free0 (_tmp16_);
				_g_free0 (_tmp14_);
				_g_free0 (_tmp12_);
				_g_free0 (_tmp9_);
				_g_free0 (_tmp7_);
				_g_free0 (word);
			}
		}
		word_collection = (_vala_array_free (word_collection, word_collection_length1, (GDestroyNotify) g_free), NULL);
	}
	result = resultString;
	return result;
}

gboolean
komorebi_utilities_canPlayVideos (void)
{
	gboolean result;
	result = TRUE;
	return result;
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

static gssize
_vala_array_length (gpointer array)
{
	gssize length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}

